export function jobProgressPercent(job){const n=Number(job.progress);if(!Number.isFinite(n))return 0;return Math.round(Math.max(0,Math.min(100,n*((job.progressUnit==='percent'||job.productionRun||job.type==='research')?1:100))));}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const active=new Set(['queued','loading','running','staging','validating','cancelling']);

/** A product-owned production entry. Browser clients supply a brief, never a model graph or path. */
export function createCinematicStudio({store,api,refresh,onError,onAction}){
  const jobs=()=>store.state.jobs.filter(j=>j.projectId===store.project?.id);
  const latest=()=>jobs().filter(j=>j.productionRun===true).sort((a,b)=>Number(active.has(b.status))-Number(active.has(a.status))||String(b.createdAt||'').localeCompare(String(a.createdAt||'')))[0];
  const stageAsset=job=>job?.output?.assetId||job?.output?.assets?.video||job?.output?.assets?.image;
  function superseded(job){
    const saved=store.project?.latestOutput;if(!job||!saved||(!saved.videoAssetId&&!saved.jobId)||active.has(job.status))return false;
    if(saved.jobId===job.id&&(!saved.videoAssetId||saved.videoAssetId===stageAsset(job)))return false;
    const savedJob=jobs().find(j=>j.id===saved.jobId);
    if(savedJob&&(Number(job.revision)>Number(savedJob.revision)||Date.parse(job.createdAt)>Date.parse(savedJob.createdAt)))return false;
    return true;
  }
  let rendered='',working=false,startFlight=null;
  function start(brief,sessionId='main'){
    if(startFlight)return startFlight;
    startFlight=startRequest(brief,sessionId).finally(()=>{startFlight=null;});return startFlight;
  }
  async function startRequest(brief,sessionId){
    if(!store.project)throw Error('Save a project before producing.');
    const projectId=store.project.id;
    const result=await api(`/projects/${projectId}/production-run`,{method:'POST',body:JSON.stringify({expectedRevision:store.project.revision,brief,sessionId})});
    if(store.project?.id===projectId)store.project=result.project;await refresh();return result;
  }
  function html(){
    const job=latest(),saved=store.project?.latestOutput;
    if(saved?.videoAssetId&&!(saved.jobId===job?.id&&saved.videoAssetId===stageAsset(job))||saved&&['blocked','rejected'].includes(saved.status)&&!job){
      const previous=superseded(job),stage=job?stagePanel(job,{previous}):'';
      return savedOutputPanel()+(stage?previous?`<details class="production-previous"><summary>Previous production stage · retained for history</summary><p class="meta">This earlier stage is not the current saved output. Review the current export above.</p>${stage}</details>`:`<div class="chat-message-meta">New production stage · current saved output retained above</div>${stage}`:'');
    }
    return job?stagePanel(job):'';
  }
  function savedOutputPanel(){
    const h=escape,p=store.project,saved=p.latestOutput,job=jobs().find(j=>j.id===saved.jobId),out=job?.output||{},provenance=saved.provenance||{},verification=saved.verification||out.verification||{},checks=verification.checks||{};
    const asset=store.state.assets?.find(a=>a.id===saved.videoAssetId&&a.projectId===p.id&&(a.kind==='video'||a.mime?.startsWith('video/'))),blocked=saved.status==='blocked';
    const hash=provenance.outputHash,source=({edited:'Edited locally',imported:'Imported media',generated:'Locally generated',upscaled:'Upscaled output',fallback:'Fallback output'})[provenance.generationStatus]||'Source method recorded below';
    const status=({verified:'Technical checks passed · visual review remains separate',reviewed:'Review recorded',review_required:'Awaiting visual review',rejected:'Rejected output',blocked:'Output blocked'})[saved.status]||String(saved.status||'Saved output').replaceAll('_',' ');
    const resolution=provenance.deliveryResolution||provenance.finalResolution||checks.resolution?.actual||{},renderRevision=out.revision??job?.revision;
    const audio=checks.audio?.ok&&checks.audio.actual?.codec?'Audio track present':checks.audio?.actual==='missing'?'No audio track recorded':'Audio status in export evidence';
    const captions=checks.captions?.ok&&/cue.*present/i.test(String(checks.captions.actual))?'Captions recorded in this render':'Caption status in export evidence';
    const layers=Array.isArray(out.audioLayers)?out.audioLayers.length:0,evidenceMismatch=out.provenance?.outputHash&&hash&&out.provenance.outputHash!==hash;
    return `<section class="chat-card cinematic-production" aria-label="Current saved output" data-current-output="${h(saved.videoAssetId||'')}" data-project-id="${h(p.id)}" data-output-hash="${h(hash||'')}"><div class="chat-message-meta">Current saved output · ${h(status)}</div><strong>${h(p.name||'Your video')}</strong><p class="meta">${renderRevision!==undefined?`Rendered from revision ${Number(renderRevision)} · `:''}current project revision ${Number(p.revision)}</p>${asset&&!blocked?`<video class="production-candidate" controls preload="metadata" playsinline src="/media/${encodeURIComponent(asset.id)}"></video><div class="chat-actions"><a class="btn primary" href="/media/${encodeURIComponent(asset.id)}" download="${h(p.name||'VYREALM-edit')}.mp4">Download current MP4</a><button class="btn" data-chat-action="export">Review current export</button><button class="btn ghost" data-chat-action="timeline">Edit timeline</button></div>`:`<p class="chat-diagnostic" role="status">${blocked?'The latest output is blocked. Inspect its diagnostic in Export.':'The current output media is unavailable in this project. It has not been replaced by an earlier stage.'}</p><button class="btn" data-chat-action="export">Open current export</button>`}<p class="meta">${h(source)} · ${Number(resolution.width)||'?'} × ${Number(resolution.height)||'?'}${Number.isFinite(Number(checks.duration?.actual))?` · ${Number(checks.duration.actual)} seconds`:''}</p><p class="meta">${h(audio)}${layers?` · ${layers} mixed audio layer${layers===1?'':'s'}`:''} · ${h(captions)}</p>${evidenceMismatch?'<p class="chat-error">The saved output and job hashes differ. Inspect the evidence before review.</p>':''}<details class="meta"><summary>Current output evidence</summary><p>Asset ${h(saved.videoAssetId||'Unavailable')}</p><p>Job ${h(saved.jobId||'Not recorded')}</p><p>SHA256 ${h(hash||'Not recorded')}</p><p>Provider ${h(provenance.providerId||'Not recorded')} · ${h(provenance.sourceMethod||'Not recorded')}</p></details></section>`;
  }
  function stagePanel(job,{previous=false}={}){
    if(job.runKind==='raw-footage')return rawPanel(job,{previous});
    const h=escape,output=job.output||{},assetId=output.assetId||output.assets?.image;
    const percent=Math.max(0,Math.min(100,Number(job.progress)||0));
    const reviewable=!previous&&job.status==='review_required'&&assetId;
    return `<section class="chat-card cinematic-production" aria-label="Current video production"><div class="chat-message-meta">VYREALM production · ${h(job.status.replaceAll('_',' '))}</div><strong>${h(job.stage||'Preparing your trailer')}</strong>${active.has(job.status)?`<progress aria-label="Production progress" max="100" value="${percent}"></progress><p class="meta">One local GPU job. The source image is reviewed before animation.</p><button class="btn ghost" data-production-cancel="${h(job.id)}">Stop this job</button>`:''}${job.error?`<p class="chat-error">${h(job.error)}</p>`:''}${assetId?`<img class="production-candidate" src="/media/${encodeURIComponent(assetId)}" alt="Generated Arjuna casting candidate awaiting costume, face and setting review"><p class="meta">Locally generated still · ${h(output.provenance?.modelId||'model recorded in receipt')} · ${h(output.provenance?.sourceResolution?.width||'')} × ${h(output.provenance?.sourceResolution?.height||'')} · ${Number.isFinite(output.provenance?.renderTimeMs)?`${Math.round(output.provenance.renderTimeMs/1000)} seconds`:''}. This is a casting image, not the finished trailer.</p>`:''}${reviewable?`<form id="productionReview" data-job-id="${h(job.id)}" data-output-hash="${h(output.provenance?.outputHash)}" data-project-id="${h(job.projectId)}"><p>Check the clean-shaven character, ivory and saffron draped costume, low diadem, coherent hands and bow, and the chariot setting. Reject a mismatch before animation.</p><label class="field" for="productionReviewNotes">Inspection notes<textarea id="productionReviewNotes" name="notes" rows="3" maxlength="4000" required placeholder="Describe what you can actually see, including any mismatch."></textarea></label><div class="chat-actions"><button class="btn" type="submit" name="verdict" value="rejected">Reject casting</button><button class="btn primary" type="submit" name="verdict" value="passed">Accept casting reference</button></div></form>`:''}${output.review?.notes?`<p class="meta">Review: ${h(output.review.notes)}</p>`:''}<details class="meta"><summary>Generation evidence</summary><p>Job ${h(job.id)}</p><p>Source SHA256 ${h(output.provenance?.outputHash||'Pending')}</p><p>Provider ${h(output.provenance?.providerId||'Awaiting provider')}</p></details></section>`;
  }
  function rawPanel(job,{previous=false}={}){
    const h=escape,out=job.output||{},id=out.assetId||out.assets?.video,reviewable=!previous&&job.status==='review_required'&&id;
    const sourceNotice=out.audioStatus==='silent-source'?'The uploaded source is silent. This edit has no audible soundtrack.':out.audioStatus==='no-audio'?'The uploaded source has no audio track.':null;
    const notices=[...(sourceNotice?[sourceNotice]:[]),...(out.diagnostics||[]).filter(d=>!['RAW_REVIEW_REQUIRED','RAW_SOURCE_SILENT'].includes(d.code)).map(d=>d.message)];
    return `<section class="chat-card cinematic-production" aria-label="Current video production"><div class="chat-message-meta">Your footage · ${h(job.status.replaceAll('_',' '))}</div><strong>${h(job.stage||'Preparing your edit')}</strong>${active.has(job.status)?`<progress aria-label="Production progress" max="100" value="${jobProgressPercent(job)}"></progress><p class="meta">Editing on this computer. Your original files are retained.</p><button class="btn ghost" data-production-cancel="${h(job.id)}">Stop this edit</button>`:''}${job.error?`<p class="chat-error">${h(job.error)}</p>`:''}${id?`<video class="production-candidate" controls preload="metadata" playsinline src="/media/${encodeURIComponent(id)}"></video><div class="chat-actions"><a class="btn primary" href="/media/${encodeURIComponent(id)}" download="VYREALM-edit.mp4">Download MP4</a><button class="btn ghost" data-chat-action="timeline">Edit timeline</button></div><p class="meta">Edited from your uploaded video · ${h(out.captionStatus||'caption status in report')} · source generation: none.</p>`:''}${notices.map(message=>`<p class="chat-diagnostic" role="status">${h(message)}</p>`).join('')}${reviewable?`<form id="productionReview" data-job-id="${h(job.id)}" data-output-hash="${h(out.provenance?.outputHash)}" data-project-id="${h(job.projectId)}"><label class="field" for="productionReviewNotes">Review the picture, sound and captions<textarea id="productionReviewNotes" name="notes" rows="2" maxlength="4000" required placeholder="Record anything that needs to change."></textarea></label><div class="chat-actions"><button class="btn" type="submit" name="verdict" value="rejected">Needs changes</button><button class="btn primary" type="submit" name="verdict" value="passed">Approve this edit</button></div></form>`:''}${out.review?.notes?`<p class="meta">Review: ${h(out.review.notes)}</p>`:''}<details class="meta"><summary>Source and export details</summary><p>Job ${h(job.id)}</p><p>SHA256 ${h(out.provenance?.outputHash||'Pending')}</p><p>${h(out.provenance?.sourceMethod||'Uploaded media')} · ${h(out.verification?.width||'')} × ${h(out.verification?.height||'')}</p></details></section>`;
  }
  function bind(){
    const node=document.querySelector('#chatProduction');if(!node)return;
    node.querySelectorAll('[data-chat-action]').forEach(button=>button.onclick=()=>{const panel=button.closest('[data-current-output]');if(panel&&(panel.dataset.projectId!==store.project?.id||panel.dataset.currentOutput!==store.project?.latestOutput?.videoAssetId||panel.dataset.outputHash!==String(store.project?.latestOutput?.provenance?.outputHash||''))){onError(Error('The saved output changed. Inspect the current export before continuing.'));update(true);return;}if(onAction)void Promise.resolve(onAction(button.dataset.chatAction)).catch(onError);});
    node.querySelector('[data-production-cancel]')?.addEventListener('click',async event=>{if(working)return;working=true;event.currentTarget.disabled=true;try{await api(`/production-runs/${event.currentTarget.dataset.productionCancel}/cancel`,{method:'POST',body:'{}'});await refresh();}catch(e){onError(e);}finally{working=false;update(true);}});
    node.querySelector('#productionReview')?.addEventListener('submit',async event=>{event.preventDefault();if(working)return;const job=latest(),form=event.currentTarget;if(!job)return;if(superseded(job)||job.id!==form.dataset.jobId||job.projectId!==form.dataset.projectId||job.output?.provenance?.outputHash!==form.dataset.outputHash){onError(Error('The production output changed or was superseded. Inspect the current output before recording a review.'));update(true);return;}const projectId=job.projectId;const verdict=event.submitter?.value;if(!['passed','rejected'].includes(verdict))return;working=true;try{const result=await api(`/production-runs/${job.id}/review`,{method:'POST',body:JSON.stringify({expectedOutputHash:job.output.provenance.outputHash,verdict,notes:new FormData(event.currentTarget).get('notes')})});if(store.project?.id===projectId)store.project=result.project;await refresh();}catch(e){onError(e);}finally{working=false;update(true);}});
  }
  function update(force=false){const node=document.querySelector('#chatProduction');if(!node||working)return;if(!force&&node.contains(document.activeElement))return;const next=html();if(next!==rendered||force){const videos=new Map([...node.querySelectorAll('video')].map(video=>[video.getAttribute('src'),video]));node.innerHTML=next;for(const video of node.querySelectorAll('video')){const existing=videos.get(video.getAttribute('src'));if(existing){video.replaceWith(existing);videos.delete(video.getAttribute('src'));}}rendered=next;bind();}}
  return {start,html,bind,update};
}
