export function jobProgressPercent(job){const n=Number(job.progress);if(!Number.isFinite(n))return 0;return Math.round(Math.max(0,Math.min(100,n*((job.progressUnit==='percent'||job.productionRun||job.type==='research')?1:100))));}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const active=new Set(['queued','running','cancelling']);

/** A product-owned production entry. Browser clients supply a brief, never a model graph or path. */
export function createCinematicStudio({store,api,refresh,onError,onAction}){
  const latest=()=>store.state.jobs.filter(j=>j.projectId===store.project?.id&&j.productionRun===true).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];
  let rendered='',working=false,startFlight=null;
  function start(brief,sessionId='main'){
    if(startFlight)return startFlight;
    startFlight=startRequest(brief,sessionId).finally(()=>{startFlight=null;});return startFlight;
  }
  async function startRequest(brief,sessionId){
    if(!store.project)throw Error('Save a project before producing.');
    const projectId=store.project.id;
    const result=await api(`/projects/${projectId}/production-run`,{method:'POST',body:JSON.stringify({expectedRevision:store.project.revision,brief,sessionId})});
    if(store.project?.id===projectId)store.project=result.project;await refresh();return result;
  }
  function html(){
    const job=latest();if(!job)return '';
    if(job.runKind==='raw-footage')return rawPanel(job);
    const h=escape,output=job.output||{},assetId=output.assetId||output.assets?.image;
    const percent=Math.max(0,Math.min(100,Number(job.progress)||0));
    const reviewable=job.status==='review_required'&&assetId;
    return `<section class="chat-card cinematic-production" aria-label="Current video production"><div class="chat-message-meta">VYREALM production · ${h(job.status.replaceAll('_',' '))}</div><strong>${h(job.stage||'Preparing your trailer')}</strong>${active.has(job.status)?`<progress aria-label="Production progress" max="100" value="${percent}"></progress><p class="meta">One local GPU job. The source image is reviewed before animation.</p><button class="btn ghost" data-production-cancel="${h(job.id)}">Stop this job</button>`:''}${job.error?`<p class="chat-error">${h(job.error)}</p>`:''}${assetId?`<img class="production-candidate" src="/media/${encodeURIComponent(assetId)}" alt="Generated Arjuna casting candidate awaiting costume, face and setting review"><p class="meta">Locally generated still · ${h(output.provenance?.modelId||'model recorded in receipt')} · ${h(output.provenance?.sourceResolution?.width||'')} × ${h(output.provenance?.sourceResolution?.height||'')} · ${Number.isFinite(output.provenance?.renderTimeMs)?`${Math.round(output.provenance.renderTimeMs/1000)} seconds`:''}. This is a casting image, not the finished trailer.</p>`:''}${reviewable?`<form id="productionReview" data-job-id="${h(job.id)}" data-output-hash="${h(output.provenance?.outputHash)}" data-project-id="${h(job.projectId)}"><p>Check the clean-shaven character, ivory and saffron draped costume, low diadem, coherent hands and bow, and the chariot setting. Reject a mismatch before animation.</p><label class="field" for="productionReviewNotes">Inspection notes<textarea id="productionReviewNotes" name="notes" rows="3" maxlength="4000" required placeholder="Describe what you can actually see, including any mismatch."></textarea></label><div class="chat-actions"><button class="btn" type="submit" name="verdict" value="rejected">Reject casting</button><button class="btn primary" type="submit" name="verdict" value="passed">Accept casting reference</button></div></form>`:''}${output.review?.notes?`<p class="meta">Review: ${h(output.review.notes)}</p>`:''}<details class="meta"><summary>Generation evidence</summary><p>Job ${h(job.id)}</p><p>Source SHA256 ${h(output.provenance?.outputHash||'Pending')}</p><p>Provider ${h(output.provenance?.providerId||'Awaiting provider')}</p></details></section>`;
  }
  function rawPanel(job){
    const h=escape,out=job.output||{},id=out.assetId||out.assets?.video,reviewable=job.status==='review_required'&&id;
    const sourceNotice=out.audioStatus==='silent-source'?'The uploaded source is silent. This edit has no audible soundtrack.':out.audioStatus==='no-audio'?'The uploaded source has no audio track.':null;
    const notices=[...(sourceNotice?[sourceNotice]:[]),...(out.diagnostics||[]).filter(d=>!['RAW_REVIEW_REQUIRED','RAW_SOURCE_SILENT'].includes(d.code)).map(d=>d.message)];
    return `<section class="chat-card cinematic-production" aria-label="Current video production"><div class="chat-message-meta">Your footage · ${h(job.status.replaceAll('_',' '))}</div><strong>${h(job.stage||'Preparing your edit')}</strong>${active.has(job.status)?`<progress aria-label="Production progress" max="100" value="${jobProgressPercent(job)}"></progress><p class="meta">Editing on this computer. Your original files are retained.</p><button class="btn ghost" data-production-cancel="${h(job.id)}">Stop this edit</button>`:''}${job.error?`<p class="chat-error">${h(job.error)}</p>`:''}${id?`<video class="production-candidate" controls preload="metadata" playsinline src="/media/${encodeURIComponent(id)}"></video><div class="chat-actions"><a class="btn primary" href="/media/${encodeURIComponent(id)}" download="VYREALM-edit.mp4">Download MP4</a><button class="btn ghost" data-chat-action="timeline">Edit timeline</button></div><p class="meta">Edited from your uploaded video · ${h(out.captionStatus||'caption status in report')} · source generation: none.</p>`:''}${notices.map(message=>`<p class="chat-diagnostic" role="status">${h(message)}</p>`).join('')}${reviewable?`<form id="productionReview" data-job-id="${h(job.id)}" data-output-hash="${h(out.provenance?.outputHash)}" data-project-id="${h(job.projectId)}"><label class="field" for="productionReviewNotes">Review the picture, sound and captions<textarea id="productionReviewNotes" name="notes" rows="2" maxlength="4000" required placeholder="Record anything that needs to change."></textarea></label><div class="chat-actions"><button class="btn" type="submit" name="verdict" value="rejected">Needs changes</button><button class="btn primary" type="submit" name="verdict" value="passed">Approve this edit</button></div></form>`:''}${out.review?.notes?`<p class="meta">Review: ${h(out.review.notes)}</p>`:''}<details class="meta"><summary>Source and export details</summary><p>Job ${h(job.id)}</p><p>SHA256 ${h(out.provenance?.outputHash||'Pending')}</p><p>${h(out.provenance?.sourceMethod||'Uploaded media')} · ${h(out.verification?.width||'')} × ${h(out.verification?.height||'')}</p></details></section>`;
  }
  function bind(){
    const node=document.querySelector('#chatProduction');if(!node)return;
    node.querySelectorAll('[data-chat-action]').forEach(button=>button.onclick=()=>{if(onAction)void Promise.resolve(onAction(button.dataset.chatAction)).catch(onError);});
    node.querySelector('[data-production-cancel]')?.addEventListener('click',async event=>{if(working)return;working=true;event.currentTarget.disabled=true;try{await api(`/production-runs/${event.currentTarget.dataset.productionCancel}/cancel`,{method:'POST',body:'{}'});await refresh();}catch(e){onError(e);}finally{working=false;update(true);}});
    node.querySelector('#productionReview')?.addEventListener('submit',async event=>{event.preventDefault();if(working)return;const job=latest(),form=event.currentTarget;if(!job)return;if(job.id!==form.dataset.jobId||job.projectId!==form.dataset.projectId||job.output?.provenance?.outputHash!==form.dataset.outputHash){onError(Error('The casting candidate changed. Inspect the current image before recording a review.'));update(true);return;}const projectId=job.projectId;const verdict=event.submitter?.value;if(!['passed','rejected'].includes(verdict))return;working=true;try{const result=await api(`/production-runs/${job.id}/review`,{method:'POST',body:JSON.stringify({expectedOutputHash:job.output.provenance.outputHash,verdict,notes:new FormData(event.currentTarget).get('notes')})});if(store.project?.id===projectId)store.project=result.project;await refresh();}catch(e){onError(e);}finally{working=false;update(true);}});
  }
  function update(force=false){const node=document.querySelector('#chatProduction');if(!node||working)return;if(!force&&node.contains(document.activeElement))return;const next=html();if(next!==rendered||force){node.innerHTML=next;rendered=next;bind();}}
  return {start,html,bind,update};
}
