const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hash=value=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
const channel=value=>typeof value==='string'&&/^UC[A-Za-z0-9_-]{22}$/.test(value);
const PENDING_KEY='vyrealm:youtube-upload-pending:v1';
const messages={THUMBNAIL_PERMISSION:'YouTube denied this thumbnail. Check custom-thumbnail eligibility and channel permissions; the video is retained.',YOUTUBE_THUMBNAIL_MISMATCH:'This thumbnail does not match the uploaded video. Create and review its paired thumbnail first.',YOUTUBE_CHANNEL_MISMATCH:'The connected channel changed. Confirm its identity in Settings before uploading.',YOUTUBE_NOT_CONNECTED:'Connect your own YouTube channel in Settings first.',YOUTUBE_SCOPE_REQUIRED:'Reconnect with upload and channel-read access before uploading.',YOUTUBE_TOKEN_REFRESH_FAILED:'YouTube access could not be renewed. Reconnect your own account in Settings.',YOUTUBE_REVIEW_REQUIRED:'Review the exact current export before uploading.',YOUTUBE_REVISION_CONFLICT:'The project changed. Review the current export before creating a new upload.',YOUTUBE_FILE_CHANGED:'The reviewed file changed. Review the exact current file before uploading.',YOUTUBE_UPLOAD_BUSY:'Another upload is active. Wait or pause it before continuing.',YOUTUBE_BUSY:'A YouTube action is still active. Wait, then retry.',YOUTUBE_REQUEST_CONFLICT:'This saved request conflicts with the recorded upload. Refresh its receipt before continuing.'};
function validRequest(value){return value&&/^[a-f0-9-]{36}$/.test(value.requestId||'')&&typeof value.projectId==='string'&&value.projectId.length<=200&&Number.isSafeInteger(value.expectedRevision)&&value.expectedRevision>0&&hash(value.expectedOutputHash)&&channel(value.expectedChannelId)&&value.confirmed===true&&typeof value.containsSyntheticMedia==='boolean'&&typeof value.metadata?.title==='string'&&value.metadata.title.trim().length>0&&value.metadata.title.length<=100&&typeof value.metadata.description==='string'&&value.metadata.description.length<=5000&&typeof value.metadata.selfDeclaredMadeForKids==='boolean'&&value.metadata.privacyStatus==='private';}
const YT_MARK='<svg class="yt-mark" width="20" height="14" viewBox="0 0 28 20" fill="none" aria-hidden="true" focusable="false"><rect width="28" height="20" rx="5.6" fill="#FF0033"/><path d="M11.2 5.9v8.2l7-4.1z" fill="#fff"/></svg>';
export function createYouTubeUpload({api,getProject,onConnect=()=>{},storage}){
 let identity='',draftProjectId='',fields={},status=null,jobs=[],busy='',error='',request=null,root=null,timer=null,loading=null,disposed=true,epoch=0,statusReadable=false,storageError=false;
 try{storage??=globalThis.localStorage;const saved=storage?.getItem(PENDING_KEY);if(saved){const parsed=JSON.parse(saved);if(!validRequest(parsed))throw Error();request=parsed;}}catch{storageError=true;error='The saved upload request cannot be read. Restore this browser’s local storage before starting another upload.';}
 const locked=()=>Boolean(busy||request||storageError);
 const saveRequest=value=>{try{if(!storage)throw Error();const text=JSON.stringify(value);storage.setItem(PENDING_KEY,text);if(storage.getItem(PENDING_KEY)!==text)throw Error();request=value;}catch{throw Object.assign(Error(),{safeMessage:'Could not save upload retry protection. Check available local storage before uploading.'});}};
 const clearRequest=()=>{try{storage.removeItem(PENDING_KEY);if(storage.getItem(PENDING_KEY)!==null)throw Error();request=null;}catch{throw Object.assign(Error(),{safeMessage:'The upload is recorded, but retry protection could not be cleared. Restore local storage and refresh.'});}};
 const project=()=>getProject?.(),post=(path,body={})=>api(path,{method:'POST',body:JSON.stringify(body)});
 function syncProject(){const p=project(),next=p?`${p.id}:${p.revision}:${p.latestOutput?.provenance?.outputHash||''}`:'';if(next!==identity){const keepDraft=Boolean(p&&draftProjectId===p.id&&Object.hasOwn(fields,'title'));identity=next;draftProjectId=p?.id||'';fields=request?.projectId===p?.id?{title:request.metadata.title,description:request.metadata.description,synthetic:request.containsSyntheticMedia,audience:request.metadata.selfDeclaredMadeForKids?'yes':'no',confirmed:true}:keepDraft?{...fields,confirmed:false}:{title:p?.creatorPack?.metadata?.title||p?.title||p?.name||'',description:p?.creatorPack?.metadata?.description||'',synthetic:true,audience:'',confirmed:false};if(!storageError)error=keepDraft&&!request?'The project was updated. Your upload details are retained; confirm the current export and destination again.':'';jobs=[];}}
 const eligible=()=>{const p=project();return p?.latestOutput?.status==='reviewed'&&hash(p.latestOutput?.provenance?.outputHash);};
 function thumbnailView(job){
  const thumb=project()?.thumbnailStudio,out=job.output||{};
  if(job.status!=='succeeded'||!thumb?.assets?.upload||!hash(thumb.artifacts?.upload?.sha256)||thumb.sourceHash!==out.sha256)return '';
  const accepted=out.thumbnail?.status==='uploaded'&&out.thumbnail?.thumbnailHash===thumb.artifacts.upload.sha256;
  return `<div class="youtube-thumbnail-review"><p class="meta">Thumbnail for this exact video</p><img src="/media/${esc(thumb.assets.upload)}" alt="${esc(thumb.title||'Selected video thumbnail')}" style="width:320px;max-width:100%;height:auto;display:block;margin:12px 0;border-radius:8px"><p class="meta">${accepted?'YouTube accepted this thumbnail.':out.thumbnail?.status==='failed'?'The video is retained. The thumbnail still needs attention.':'Review the image before attaching it to this private video.'}</p>${accepted?'':`<button class="btn small" data-yt-thumbnail="${esc(job.id)}" data-thumbnail-job="${esc(thumb.jobId)}" data-thumbnail-hash="${esc(thumb.artifacts.upload.sha256)}" ${busy?'disabled':''}>Upload this thumbnail</button>`}</div>`;
 }
 function body(){syncProject();const p=project(),connected=status?.connected&&channel(status.connectedChannel?.id),allowed=connected&&status.upload==='authorized-not-verified';
  return `<div class="panel-title"><div><span class="eyebrow">Your channel · optional online action</span><h3>Upload privately to YouTube</h3></div><span class="status">PRIVATE ONLY</span></div>
  <p class="meta">Send the reviewed export to your authorized channel. Nothing is published publicly. YouTube processing is checked separately after transfer.</p>
  <p role="status">${status?connected?`Destination: <strong>${esc(status.connectedChannel.title)}</strong><br><span class="meta">${esc(status.connectedChannel.id)}</span>`:'Connect your own YouTube channel in Settings.':'Reading channel connection…'}</p>
  ${!connected?'<button class="btn" type="button" id="ytUploadConnect">Connect your channel</button>':!allowed?'<p class="meta">Upload and channel-read consent is required. Reconnect in Settings with upload access.</p><button class="btn" id="ytUploadConnect">Open YouTube settings</button>':''}
  ${!eligible()?'<p class="meta">This export needs an exact-file visual review before it can be uploaded. Open its completed render in Jobs and record the review.</p>':''}
  ${request?`<p class="meta" role="status">A saved upload request is awaiting its receipt. Retry the same upload or refresh to recover it. Its title, audience and destination stay locked. Saved revision ${request.expectedRevision} · source ${esc(request.expectedOutputHash.slice(0,12))} · channel ${esc(request.expectedChannelId)}.${request.projectId!==p?.id?' Reopen its original project to retry.':''}</p>`:''}
  <form id="ytUploadForm"><div class="field"><label for="ytUploadTitle">Video title</label><input id="ytUploadTitle" maxlength="100" required value="${esc(fields.title)}" ${locked()?'disabled':''}></div><div class="field"><label for="ytUploadDescription">Description</label><textarea id="ytUploadDescription" maxlength="5000" rows="3" ${locked()?'disabled':''}>${esc(fields.description)}</textarea></div><div class="field"><label for="ytUploadAudience">Audience</label><select id="ytUploadAudience" required ${locked()?'disabled':''}><option value="" ${fields.audience===''?'selected':''}>Choose the appropriate audience</option><option value="no" ${fields.audience==='no'?'selected':''}>Not made for kids</option><option value="yes" ${fields.audience==='yes'?'selected':''}>Made for kids</option></select></div><label class="check"><input id="ytUploadSynthetic" type="checkbox" ${fields.synthetic?'checked':''} ${locked()?'disabled':''}> Contains realistic altered or synthetic media</label><label class="check"><input id="ytUploadConfirm" type="checkbox" ${fields.confirmed?'checked':''} ${locked()?'disabled':''}> Upload this reviewed export privately to ${esc(status?.connectedChannel?.title||'my connected channel')}.</label><div class="panel-actions"><button class="btn primary youtube" type="submit" ${!allowed||!statusReadable||busy||storageError||(request?request.projectId!==p?.id:!eligible()||!fields.confirmed)?'disabled':''}>${YT_MARK}${busy==='upload'?'Starting private upload…':request?'Retry same upload':'Upload private video'}</button><button class="btn ghost" id="ytUploadRefresh" type="button" ${busy?'disabled':''}>Refresh uploads</button></div></form>
  ${error?`<p role="alert">${esc(error)}</p>`:''}
  <div>${jobs.map(job=>{const out=job.output||{},percent=Math.round(Math.max(0,Math.min(1,job.progress||0))*100),url=/^[A-Za-z0-9_-]{11}$/.test(out.videoId||'')?`https://www.youtube.com/watch?v=${out.videoId}`:null,processed=job.status==='succeeded'&&out.state==='uploaded_private'&&out.processingVerified===true&&out.processing?.status==='succeeded'&&out.privacyStatus==='private',summary=processed?'Private video ready':job.status==='succeeded'?(out.processing?.status==='failed'?'Private transfer completed; YouTube processing failed':'Private transfer completed; processing not yet verified'):{queued:'Private upload queued',running:'Uploading privately',cancelling:'Pausing upload',cancelled:'Upload paused',failed:'Upload needs attention'}[job.status]||'Upload status unavailable';return `<article class="panel" data-yt-job="${esc(job.id)}" style="margin-top:16px;padding:16px"><strong>${summary}</strong><p class="meta">${esc(job.status)} · ${percent}% transferred${processed?' · YouTube processing verified':''}</p>${['queued','running','cancelling'].includes(job.status)?`<progress max="100" value="${percent}" aria-label="Upload transfer progress">${percent}%</progress>`:''}${job.error?`<p role="alert">${esc(messages[String(job.error).split(':')[0]]||'This upload stopped. Refresh its status, then resume when the connection is ready.')}</p>`:''}<div class="panel-actions">${url?`<a class="btn small" href="${url}" target="_blank" rel="noopener noreferrer">Open private video</a>`:''}${job.status==='succeeded'?`<button class="btn small" data-yt-verify="${esc(job.id)}" ${busy?'disabled':''}>Check YouTube processing</button>`:''}${['queued','running'].includes(job.status)?`<button class="btn small" data-yt-cancel="${esc(job.id)}" ${busy?'disabled':''}>Pause upload</button>`:''}${['failed','cancelled'].includes(job.status)?`<button class="btn small" data-yt-retry="${esc(job.id)}" ${busy?'disabled':''}>Resume upload</button>`:''}</div>${thumbnailView(job)}</article>`;}).join('')}</div>`;
 }
 function html(){return `<section class="panel" id="youtubeUploadPanel" style="margin-top:24px;min-width:0;overflow-wrap:anywhere"><style>#youtubeUploadPanel .panel-actions{display:flex;flex-wrap:wrap;gap:10px}#youtubeUploadPanel :is(input,textarea,select){min-width:0;max-width:100%}#youtubeUploadPanel .check{display:flex;gap:9px;align-items:flex-start;margin:12px 0;font-size:12px;line-height:1.7}#youtubeUploadPanel input[type=checkbox]{flex:0 0 auto;accent-color:#ba99eb}#youtubeUploadPanel [role=alert]{color:#edbabd;font-size:12px}#youtubeUploadPanel :is(button,input,textarea,select,a):focus-visible{outline:2px solid #d5bcf5;outline-offset:3px}@media(max-width:650px){#youtubeUploadPanel .btn{white-space:normal;min-height:44px}}</style>${body()}</section>`;}
 function paint(){const panel=root?.querySelector('#youtubeUploadPanel');if(!panel||disposed)return;const focused=panel.contains(globalThis.document?.activeElement)?globalThis.document.activeElement:null,key=focused?.id,start=focused?.selectionStart,end=focused?.selectionEnd,style=panel.querySelector('style')?.outerHTML||'';panel.innerHTML=style+body();wire(panel);if(key){const target=panel.querySelector(`#${key}`);target?.focus();if(typeof start==='number'&&target?.setSelectionRange)try{target.setSelectionRange(start,end);}catch{}}}
 function schedule(){clearTimeout(timer);if(!disposed){timer=setTimeout(()=>void update(),3000);timer.unref?.();}}
 function recorded(job,saved,full=false){return job?.id===saved.requestId&&job.type==='youtube-upload'&&job.projectId===saved.projectId&&job.revision===saved.expectedRevision&&(!full||(job.expectedOutputHash===saved.expectedOutputHash&&job.expectedChannelId===saved.expectedChannelId&&job.containsSyntheticMedia===saved.containsSyntheticMedia&&JSON.stringify(job.metadata)===JSON.stringify(saved.metadata)));}
 async function update(){if(disposed)return;syncProject();if(loading)return loading;const before=identity,generation=epoch;loading=(async()=>{try{const [next,all]=await Promise.all([api('/youtube/status'),api('/jobs')]);if(disposed||before!==identity||generation!==epoch)return;const rows=Array.isArray(all)?all:all.jobs;if(!Array.isArray(rows))throw Error();if(status?.connectedChannel?.id!==next.connectedChannel?.id&&!request)fields.confirmed=false;status=next;statusReadable=true;
  if(request){const admitted=rows.find(job=>job.id===request.requestId);if(admitted){if(!recorded(admitted,request,true))throw Error();clearRequest();fields.confirmed=false;error='';}}
  jobs=rows.filter(job=>job.type==='youtube-upload'&&job.projectId===project()?.id).slice(0,10);paint();}catch{if(!disposed&&generation===epoch){statusReadable=false;error='Could not read upload status. Refresh to reconnect to the local engine.';paint();}}finally{if(generation===epoch){loading=null;schedule();}}})();return loading;}
 async function perform(action,work){if(busy||disposed)return;busy=action;if(!storageError)error='';const generation=epoch,before=identity,active=()=>!disposed&&generation===epoch&&identity===before;paint();try{await work(active);}catch(e){if(active())error=messages[e.code]||e.safeMessage||(request?'The upload response is unresolved. Refresh or retry the same saved upload; its original details are retained.':'YouTube could not complete this action. Refresh the connection and try again.');}finally{if(generation===epoch){busy='';await update();paint();}}}
 async function submit(){return perform('upload',async active=>{const p=project();if(storageError||!statusReadable||!p||(!request&&(!eligible()||!fields.confirmed||!fields.title.trim()||!['yes','no'].includes(fields.audience)))||(request&&request.projectId!==p.id))throw Object.assign(Error(),{safeMessage:'Review the export, title, audience and destination before uploading.'});const expectedChannelId=request?.expectedChannelId||status?.connectedChannel?.id;if(!channel(expectedChannelId))throw Object.assign(Error(),{code:'YOUTUBE_NOT_CONNECTED'});
  const candidate=request||{requestId:crypto.randomUUID(),projectId:p.id,expectedRevision:p.revision,expectedOutputHash:p.latestOutput.provenance.outputHash,expectedChannelId,confirmed:true,containsSyntheticMedia:fields.synthetic,metadata:{title:fields.title.trim(),description:fields.description,selfDeclaredMadeForKids:fields.audience==='yes',privacyStatus:'private'}};
  if(!validRequest(candidate))throw Object.assign(Error(),{safeMessage:'Check the title, description, audience and exact reviewed export before uploading.'});
  const verified=await post('/youtube/verify');if(!active())return;if(!verified.connected||verified.connectedChannel?.id!==expectedChannelId||verified.channelVerification?.status!=='verified'){status=verified;if(!request)fields.confirmed=false;throw Object.assign(Error(),{code:'YOUTUBE_CHANNEL_MISMATCH'});}
  if(!request&&(project()?.id!==candidate.projectId||project()?.revision!==candidate.expectedRevision||project()?.latestOutput?.provenance?.outputHash!==candidate.expectedOutputHash))throw Object.assign(Error(),{code:'YOUTUBE_REVISION_CONFLICT'});
  if(!request)saveRequest(candidate);
  let job;try{job=await post('/youtube/upload',candidate);}catch(failure){if(failure.status>=400&&failure.status<500&&['YOUTUBE_REVISION_CONFLICT','YOUTUBE_REVIEW_REQUIRED','YOUTUBE_FILE_CHANGED','YOUTUBE_INVALID_REQUEST','YOUTUBE_CHANNEL_MISMATCH','YOUTUBE_NOT_CONNECTED','YOUTUBE_SCOPE_REQUIRED','YOUTUBE_UPLOAD_BUSY'].includes(failure.code)){clearRequest();fields.confirmed=false;}throw failure;}
  if(!active())return;if(!recorded(job,candidate))throw Error();clearRequest();fields.confirmed=false;
 });}
 function wire(panel){const on=(selector,event,fn)=>{const el=panel.querySelector(selector);if(el)el[event]=fn;};on('#ytUploadConnect','onclick',onConnect);on('#ytUploadRefresh','onclick',()=>void update());on('#ytUploadTitle','oninput',e=>{if(!locked())fields.title=e.target.value;});on('#ytUploadDescription','oninput',e=>{if(!locked())fields.description=e.target.value;});on('#ytUploadAudience','onchange',e=>{if(!locked())fields.audience=e.target.value;});on('#ytUploadSynthetic','onchange',e=>{if(!locked())fields.synthetic=e.target.checked;});on('#ytUploadConfirm','onchange',e=>{if(!locked()){fields.confirmed=e.target.checked;paint();}});on('#ytUploadForm','onsubmit',e=>{e.preventDefault();void submit();});for(const button of panel.querySelectorAll('[data-yt-thumbnail]'))button.onclick=()=>perform('thumbnail',()=>post('/youtube/uploads/'+encodeURIComponent(button.dataset.ytThumbnail)+'/thumbnail',{thumbnailJobId:button.dataset.thumbnailJob,expectedThumbnailHash:button.dataset.thumbnailHash,confirmed:true}));for(const button of panel.querySelectorAll('[data-yt-verify]'))button.onclick=()=>perform('verify',()=>post(`/youtube/uploads/${encodeURIComponent(button.dataset.ytVerify)}/verify`));for(const button of panel.querySelectorAll('[data-yt-cancel]'))button.onclick=()=>perform('cancel',()=>post(`/jobs/${encodeURIComponent(button.dataset.ytCancel)}/cancel`));for(const button of panel.querySelectorAll('[data-yt-retry]'))button.onclick=()=>perform('retry',()=>post(`/jobs/${encodeURIComponent(button.dataset.ytRetry)}/retry`));}
 function bind(element=globalThis.document){root=element;disposed=false;syncProject();const panel=root?.querySelector('#youtubeUploadPanel');if(panel){wire(panel);void update();}}
 function dispose(){disposed=true;epoch++;clearTimeout(timer);root=null;loading=null;busy='';}
 return {html,bind,update,dispose};
}
