import { test, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';

test('offline local media, Piper, Whisper, edit, three exports, download and reopen', async({page,request},testInfo)=>{
 test.skip(!process.env.VYREALM_TEST_MEDIA,'Set VYREALM_TEST_MEDIA to a licensed local five-second clip. This test does not claim imported media is model-generated.');
 const outside=[];await page.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&!['127.0.0.1','localhost'].includes(u.hostname)){outside.push(u.origin);return route.abort();}return route.continue();});
 const failures=[];page.on('pageerror',e=>failures.push(e.message));
 await page.goto('/');await page.locator('#refreshBtn:not(:disabled)').waitFor();await page.locator('.sidebar [data-nav=Dashboard]').click();await page.locator('#newProject').click();
 const name=`Offline verification ${Date.now()}`;
 await page.locator('#projectName').fill(name);await page.locator('#projectBrief').fill('A visitor in a rainy night market hears footsteps, pauses, and looks back. Edit my local footage with original voiceover and readable captions.');
 await page.locator('#createProjectBtn').click();await expect(page.locator('#produceBtn')).toBeVisible();
 const projectId=await page.evaluate(()=>localStorage.getItem('vyrelum:selectedProject'));
 const session=await request.get('/api/session');const token=(await session.json()).token;
 const headers={'X-Vyrelum-Token':token};
 const api=async path=>(await request.get(path,{headers})).json();
 const project=()=>api(`/api/projects/${projectId}`);
 await page.locator('#mediaInput').setInputFiles(process.env.VYREALM_TEST_MEDIA);
 await expect(page.locator('.timeline-clip')).toHaveCount(1);await page.locator('#saveProject').click();
 await expect.poll(async()=>(await project()).timeline?.length).toBe(1);
 await page.locator('#narrationText').fill('Someone is following me.');await page.locator('#generateNarration').click();
 await expect.poll(async()=>Boolean((await project()).latestAudio?.assetId),{timeout:120000}).toBe(true);
 await page.locator('.sidebar [data-nav=Audio]').click();await expect(page.locator('audio')).toBeVisible();
 await page.locator('#transcribeAsset').selectOption((await project()).latestAudio.assetId); await page.locator('#transcribeMedia').click();await expect.poll(async()=>Boolean((await project()).transcript?.length),{timeout:120000}).toBe(true);
 await page.locator('.sidebar [data-nav=Audio]').click();
 await expect(page.getByLabel('Caption 1 text',{exact:true})).not.toHaveValue('');
 await page.getByLabel('Caption 1 text',{exact:true}).fill('Someone is following me.');await page.locator('#saveAudioEdits').click();
 await page.locator('#soundDesignControls summary').click();await page.locator('#soundFootsteps').fill('0.7, 1.3, 2.2');await page.locator('#soundShelter').fill('3');await page.locator('#soundClimax').fill('4');
 await page.locator('#generateSoundDesign').click();await expect.poll(async()=>(await project()).audioTracks?.length,{timeout:30000}).toBe(1);
 expect((await project()).latestSoundDesign.provenance.neuralModelInvoked).toBe(false);
 await page.locator('.sidebar [data-nav=Audio]').click();await page.locator('#soundDesignControls summary').click();
 await page.getByLabel('Audio layer 1 gain',{exact:true}).fill('0.4');await page.locator('#saveSoundLayers').click();
 await expect.poll(async()=>(await project()).audioTracks[0].gain).toBe(0.4);
 await page.locator('#exportCanvas').locator('..').locator('..').getByText('Colour grade',{exact:true}).click();await page.locator('#grade-saturation').fill('0.92');await page.locator('#saveProject').click();
 const current=await project();const rejectedReference=await request.post('/api/generation/shot',{headers,data:{projectId,expectedRevision:current.revision,referenceJobId:'not-a-reviewed-generated-job',brief:'Run through a night market'}});expect(rejectedReference.status()).toBe(409);expect((await rejectedReference.json()).code).toBe('REVIEWED_REFERENCE_REQUIRED');
 const artifacts=[];
 for(const canvas of ['1920x1080','1080x1920','1080x1080']){
  await page.locator('#exportCanvas').selectOption(canvas);await page.locator('#exportFraming').selectOption('cover');
  const before=(await project()).latestOutput?.jobId;await page.locator('#renderBtn').click();
  await expect.poll(async()=>{const p=await project();return p.latestOutput?.jobId&&p.latestOutput.jobId!==before?p.latestOutput.status:null;},{timeout:120000}).toBe('verified');
  const p=await project(),job=await api(`/api/jobs/${p.latestOutput.jobId}`);
  expect(job.status).toBe('succeeded');expect(job.output.verification.ok).toBe(true);expect(p.latestOutput.provenance.generationStatus).toBe('edited');
  expect(job.output.audioLayers.length).toBe(2);expect(job.output.audioLayers[1].gain).toBe(0.4);
  expect(job.output.colorGrade.saturation).toBe(0.92);
  await page.locator('.sidebar [data-nav=Timeline]').click();
  await expect(page.locator('.source-lineage')).toContainText('Shot 1 · Imported');
  await page.locator('.source-evidence summary').click();
  await expect(page.locator('.source-evidence')).toContainText('No generation model claimed');
  await expect(page.getByRole('link',{name:'Download video',exact:true})).toHaveAttribute('data-job-id',job.id,{timeout:15000});
  const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Download video',exact:true}).click();const download=await downloadPromise;
  const dir=resolve((process.env.VYREALM_TEST_OUTPUT||'outputs/verification'));await mkdir(dir,{recursive:true});const path=join(dir,`golden-${canvas}.mp4`);await download.saveAs(path);
  const probe=JSON.parse(execFileSync(resolve('workers/tools/ffprobe.exe'),['-v','error','-show_streams','-show_format','-of','json',path],{encoding:'utf8',windowsHide:true}));const video=probe.streams.find(s=>s.codec_type==='video'),audio=probe.streams.find(s=>s.codec_type==='audio');
  expect(`${video.width}x${video.height}`).toBe(canvas);expect(video.nb_frames).toBe('120');expect(audio.sample_rate).toBe('48000');expect(Number(probe.format.duration)).toBeCloseTo(5,1);
  execFileSync(resolve('workers/tools/ffmpeg.exe'),['-v','error','-xerror','-i',path,'-f','null','-'],{windowsHide:true});
  const range=await request.get(`/media/${p.latestOutput.videoAssetId}`,{headers:{Range:'bytes=0-1023'}});expect(range.status()).toBe(206);expect((await range.body()).length).toBe(1024);
  artifacts.push({canvas,jobId:job.id,path,sourceMethod:'imported media, local Piper narration, local Whisper captions, local FFmpeg edit'});
 }
 await page.screenshot({path:join(process.env.VYREALM_TEST_OUTPUT||'outputs/verification','studio-audio-captions.png'),fullPage:true});
 const portable=await api(`/api/projects/${projectId}/export`);
 const broken=structuredClone(portable);delete broken.assets[0].data;
 const refused=await request.post('/api/projects/import',{headers,data:broken});expect(refused.status()).toBe(400);expect((await refused.json()).error).toContain('INCOMPLETE_PROJECT_BUNDLE');
 const restoredResponse=await request.post('/api/projects/import',{headers,data:portable});expect(restoredResponse.status()).toBe(201);const restored=await restoredResponse.json();
 expect(restored.audioTracks[0].assetId).not.toBe(portable.project.audioTracks[0].assetId);expect(restored.latestAudio.assetId).not.toBe(portable.project.latestAudio.assetId);expect(restored.importedHistory.revisions.length).toBe(portable.revisions.length);
 const resumed=await request.post('/api/jobs',{headers,data:{type:'render',projectId:restored.id,expectedRevision:restored.revision}});const restoredJob=await resumed.json();
 await expect.poll(async()=>(await api(`/api/jobs/${restoredJob.id}`)).status,{timeout:120000}).toBe('succeeded');
 const restoredResult=await api(`/api/jobs/${restoredJob.id}`);expect(restoredResult.output.audioLayers.length).toBe(2);expect(restoredResult.output.provenance.sources[0].upstream.generationStatus).toBe('imported');
 await page.reload();await page.locator('#refreshBtn:not(:disabled)').waitFor();await page.locator('.sidebar [data-nav=Dashboard]').click();await page.locator('.project-card').filter({hasText:name}).first().click();await expect(page.locator('video')).toBeVisible();
 await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(1);
 await page.setViewportSize({width:520,height:900});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:join(process.env.VYREALM_TEST_OUTPUT||'outputs/verification','studio-narrow.png'),fullPage:true});
 expect(failures).toEqual([]);expect(outside).toEqual([]);
 await writeFile(join(process.env.VYREALM_TEST_OUTPUT||'outputs/verification','golden-evidence.json'),JSON.stringify({projectId,artifacts,externalBrowserRequests:outside,pageErrors:failures},null,2));
});
