import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {spawn} from 'node:child_process';import {createInterface} from 'node:readline';import {once} from 'node:events';
test('real stdio initialize list call with isolated authenticated HTTP store',{timeout:20000},async t=>{
 let authorized=true,posts=0;const store=new Map([['p',{id:'p',revision:2}]]);
 const server=createServer(async(req,res)=>{res.setHeader('content-type','application/json');const send=(code,body)=>{res.writeHead(code);res.end(JSON.stringify(body));};if(req.url==='/api/session')return send(200,authorized?{token:'isolated-test-token'}:{});if(req.headers['x-vyrelum-token']!=='isolated-test-token'||!authorized)return send(401,{code:'AUTH_REQUIRED',error:'Session required'});if(req.method==='GET')return send(200,store.get('p'));posts++;let body='';for await(const chunk of req)body+=chunk;const input=JSON.parse(body);if(req.url.endsWith('/research'))return send(202,{id:'research-1',projectId:'p',revision:input.expectedRevision,type:'research',status:'running'});return send(409,{code:'CREATOR_PACK_SOURCE',error:'Render a playable edit first.'});});server.listen(0,'127.0.0.1');await once(server,'listening');
 const child=spawn(process.execPath,['mcp-server.mjs'],{cwd:new URL('..',import.meta.url),windowsHide:true,env:{...process.env,VYREALM_API:`http://127.0.0.1:${server.address().port}`},stdio:['pipe','pipe','pipe']});let seq=0;const pending=new Map();createInterface({input:child.stdout}).on('line',line=>{const response=JSON.parse(line);pending.get(response.id)?.(response);pending.delete(response.id);});child.stderr.resume();t.after(async()=>{child.stdin.end();if(child.exitCode===null)await once(child,'exit');await new Promise(r=>server.close(r));});
 const rpc=(method,params)=>new Promise(resolve=>{const id=++seq;pending.set(id,resolve);child.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});const call=async(name,args)=>JSON.parse((await rpc('tools/call',{name,arguments:args})).result.content[0].text);
 assert.equal((await rpc('initialize',{protocolVersion:'2025-03-26'})).result.protocolVersion,'2025-03-26');child.stdin.write(JSON.stringify({jsonrpc:'2.0',method:'notifications/initialized'})+'\n');const list=await rpc('tools/list');assert.ok(list.result.tools.some(t=>t.name==='prepare_creator_pack'));assert.ok(!list.result.tools.find(t=>t.name==='research_topic').description.includes('unavailable'));
 assert.equal((await call('research_topic',{projectId:'p',expectedRevision:2,query:'Earth'})).status,'failed');assert.equal(posts,0);
 assert.equal((await call('research_topic',{projectId:'p',expectedRevision:1,query:'Earth',onlineAuthorized:true})).diagnostics[0].code,'REVISION_CONFLICT');assert.equal(posts,0);
 const research=await call('research_topic',{projectId:'p',expectedRevision:2,query:'Earth',onlineAuthorized:true});assert.equal(research.status,'running');assert.equal(research.verification.status,'not-run');
 assert.equal((await call('create_thumbnail',{projectId:'p',expectedRevision:2})).diagnostics[0].code,'CREATOR_PACK_SOURCE');assert.equal(posts,2);
 authorized=false;assert.equal((await call('prepare_creator_pack',{projectId:'p',expectedRevision:2})).diagnostics[0].code,'SESSION_UNAVAILABLE');assert.equal(posts,2);
});
