import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { mkdtemp,rm } from 'node:fs/promises';
import { join,dirname,basename,resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { createYouTubeInsights } from '../publishing/youtube-insights.mjs';
import { createInsightProject } from './insight-project.mjs';
const A='UCaaaaaaaaaaaaaaaaaaaaaa',B='UCbbbbbbbbbbbbbbbbbbbbbb',at='2026-09-08T12:00:00.000Z';
async function fixture(t,{file=':memory:'}={}){
 let db=new DatabaseSync(file),connection={connected:true,connectedChannel:{id:A,title:'Own channel'}};
 db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,revision INTEGER NOT NULL,document TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE project_revisions(project_id TEXT NOT NULL,revision INTEGER NOT NULL,document TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(project_id,revision));CREATE TABLE assets(id TEXT PRIMARY KEY,project_id TEXT,document TEXT,path TEXT,created_at TEXT);');
 const make=()=>createYouTubeInsights({db,readConnection:async()=>connection,clock:()=>Date.parse(at),fetchDailyAnalytics:async q=>({...q,columnHeaders:[],rows:[]}),fetchVideoAnalytics:async q=>({...q,columnHeaders:['video','views','estimatedMinutesWatched','averageViewDuration','likes','comments','shares'].map(name=>({name})),rows:[['abcdefghijk',100,100,60,4,1,1],['bcdefghijkl',100,50,30,2,0,0],['cdefghijklm',100,40,24,1,0,0]]})});let insights=make();
 t.after(async()=>{await insights.close();db.close();});await insights.handle({pathname:'/api/youtube/insights/refresh',method:'POST',body:{channelId:A}});await insights.tick();const state=(await insights.handle({pathname:'/api/youtube/insights',method:'GET'})).body;
 return {get db(){return db;},get insights(){return insights;},state,input:{requestId:randomUUID(),channelId:A,snapshotId:state.snapshot.id,recommendationId:state.recommendations[0].id},channel:id=>connection=id?{connected:true,connectedChannel:{id,title:id}}:{connected:false,connectedChannel:null},async reopen(){await insights.close();db.close();db=new DatabaseSync(file);insights=make();}};
}
const create=(f,input=f.input)=>createInsightProject({db:f.db,insights:f.insights,input,now:()=>at});
test('uses the actual stored recommendation and records one empty canonical portrait draft',async t=>{const f=await fixture(t),p=await create(f);assert.equal(p.brief,f.state.recommendations[0].brief);assert.equal(p.name,f.state.recommendations[0].title);assert.equal(p.mode,'cinematic');assert.deepEqual(p.settings,{width:1080,height:1920,fps:24});assert.equal(p.revision,1);assert.equal(p.captionsEnabled,true);assert.deepEqual(p.timeline,[]);assert.deepEqual(p.assets,[]);assert.equal(p.latestOutput,null);assert.equal(p.insightSource.sourceMethod,'youtube-analytics-derived-hypothesis');assert.equal(p.insightSource.snapshotId,f.input.snapshotId);assert.equal(p.insightSource.evidence.observed,60);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM project_revisions').get().n,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM assets').get().n,0);});
test('concurrent and response-loss retries return one project; changed input is rejected',async t=>{const f=await fixture(t),[a,b]=await Promise.all([create(f),create(f)]);assert.equal(a.id,b.id);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM projects').get().n,1);await assert.rejects(create(f,{...f.input,recommendationId:'different'}),{code:'INSIGHT_PROJECT_REQUEST_CONFLICT'});const changed={...a,name:'User continued editing',brief:'User new brief'};f.db.prepare('UPDATE projects SET revision=?,document=? WHERE id=?').run(2,JSON.stringify(changed),a.id);const replay=await create(f);assert.equal(replay.revision,2);assert.equal(replay.brief,'User new brief');});
test('new admissions reject stale snapshot, forged text and another channel',async t=>{const f=await fixture(t);for(const input of [{...f.input,brief:'Invented winner'},{...f.input,evidence:{views:999999}}])await assert.rejects(create(f,input),{code:'INSIGHT_PROJECT_INVALID'});await assert.rejects(create(f,{...f.input,snapshotId:randomUUID()}),{code:'INSIGHT_PROJECT_SOURCE_STALE'});await assert.rejects(create(f,{...f.input,recommendationId:'unknown'}),{code:'INSIGHT_PROJECT_SOURCE_STALE'});await assert.rejects(create(f,{...f.input,channelId:B}),{code:'INSIGHT_PROJECT_CHANNEL_CHANGED'});f.channel(null);await assert.rejects(create(f),{code:'INSIGHT_PROJECT_CHANNEL_REQUIRED'});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM projects').get().n,0);});
test('canonical snapshot tampering cannot turn a supplied service response into evidence',async t=>{const f=await fixture(t);const stored=JSON.parse(f.db.prepare('SELECT document FROM youtube_insights_snapshots WHERE id=?').get(f.input.snapshotId).document);stored.reports.video.rows[0][1]=99999;f.db.prepare('UPDATE youtube_insights_snapshots SET document=? WHERE id=?').run(JSON.stringify(stored),stored.id);await assert.rejects(create(f),{code:'INSIGHT_PROJECT_EVIDENCE_INVALID'});assert.equal(f.db.prepare('SELECT COUNT(*) n FROM projects').get().n,0);});
test('a fabricated recommendation from a replaced handle is rejected against stored metrics',async t=>{const f=await fixture(t);const fake={handle:async()=>({status:200,body:{...f.state,recommendations:[{...f.state.recommendations[0],brief:'Fake viral claim'}]}})};await assert.rejects(createInsightProject({db:f.db,insights:fake,input:f.input,now:()=>at}),{code:'INSIGHT_PROJECT_EVIDENCE_INVALID'});});
test('transaction rollback leaves no partial draft when revision persistence fails',async t=>{const f=await fixture(t);f.db.exec("CREATE TRIGGER break_revision BEFORE INSERT ON project_revisions BEGIN SELECT RAISE(ABORT,'fixture interruption'); END;");await assert.rejects(create(f));assert.equal(f.db.prepare('SELECT COUNT(*) n FROM projects').get().n,0);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM insight_project_requests').get().n,0);f.db.exec('DROP TRIGGER break_revision');assert.ok((await create(f)).id);});
test('idempotency survives SQLite close/reopen and a newer analytics snapshot',async t=>{const dir=await mkdtemp(join(tmpdir(),'vyrealm-insight-project-'));const f=await fixture(t,{file:join(dir,'projects.sqlite')});t.after(async()=>{if(dirname(dir)===resolve(tmpdir())&&basename(dir).startsWith('vyrealm-insight-project-'))await rm(dir,{recursive:true,force:true});});const p=await create(f);await f.reopen();await f.insights.handle({pathname:'/api/youtube/insights/refresh',method:'POST',body:{channelId:A}});await f.insights.tick();assert.equal((await create(f)).id,p.id);await assert.rejects(create(f,{...f.input,requestId:randomUUID()}),{code:'INSIGHT_PROJECT_SOURCE_STALE'});f.channel(B);await assert.rejects(create(f),{code:'INSIGHT_PROJECT_CHANNEL_CHANGED'});});
