import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { createOriginalGenerationService, validateOriginalRequest, cancelOriginalProviderPrompt, preflightOriginalGeneration } from './original-generation-service.mjs';
import { wanWorkflow, WAN_MODELS } from './neural-production.mjs';
import { hashJson } from './generation-gate.mjs';
import { verifyKeyframeEvidence, verifyOwnedGeneratedKeyframe, produceLocalKeyframe } from './keyframe-production.mjs';
import { produceReviewedKeyframeMotion, verifyReviewedMotionEvidence, validateReviewedMotionRequest, originalMotionProfile, reviewedMotionWorkflow } from './reviewed-keyframe-motion.mjs';
import { LTX_MODELS, ltxWorkflow } from './ltx-production.mjs';
import { verifyReviewTarget } from './verify-review-target.mjs';

const root=fileURLToPath(new URL('..',import.meta.url)),exec=promisify(execFile);
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const brief='An original handmade ivory ceramic cup beside a rain-streaked window. Steam curls and raindrops move. Detailed glaze, wood grain, gentle lateral camera motion. No text.';
const input={projectId:'project-1',expectedRevision:1,brief,seed:90820261};
async function imageFixture({jobRoot,request}){
 const stage=path.join(jobRoot,'keyframe');await fs.mkdir(path.join(stage,'frames'),{recursive:true});const image=path.join(stage,'frames','00000.png');
 // Synthetic CPU bars test receipt mechanics only, never model quality or the real catalogue.
 await exec(path.join(root,'workers/tools/ffmpeg.exe'),['-v','error','-f','lavfi','-i',`testsrc2=s=${request.width}x${request.height}`,'-frames:v','1','-threads','1','-y',image],{windowsHide:true,timeout:30000});
 const workflow=wanWorkflow({...request,frames:1,prefix:`vyrealm/${path.basename(jobRoot)}/keyframe`}),workflowHash=hashJson(workflow),promptId='isolated-fixture-prompt',descriptor={filename:'keyframe_00001_.png',subfolder:`vyrealm/${path.basename(jobRoot)}`,type:'output'},bytes=await fs.readFile(image),outputHash=sha(bytes);
 await fs.writeFile(path.join(stage,'workflow.json'),JSON.stringify(workflow));await fs.writeFile(path.join(stage,'history.json'),JSON.stringify({prompt:[0,promptId,workflow],status:{completed:true,status_str:'success'},outputs:{'10':{images:[descriptor]}}}));await fs.writeFile(path.join(stage,'provider.jsonl'),['submitted','completed'].map(event=>JSON.stringify({event,promptId,workflowHash})).join('\n'));await fs.writeFile(path.join(stage,'frames.json'),JSON.stringify([{index:0,path:'frames/00000.png',sha256:outputHash,providerOutput:descriptor}]));
 const evidence=await verifyKeyframeEvidence({jobRoot,request}),receipt={schemaVersion:1,kind:'generated-keyframe',status:'review_required',validated:true,sourceMethod:'local-generated-keyframe',provenance:{status:'generated',generationStatus:'generated',mediaKind:'image',providerId:'comfyui-local',modelId:WAN_MODELS.diffusion,promptId,workflowHash,evidenceHash:evidence.evidenceHash,outputHash,seed:request.seed,prompt:request.prompt,...(request.negativePrompt?{negativePrompt:request.negativePrompt}:{}),keyframe:{promptId,outputHash},semanticQuality:'unreviewed'},verification:{ok:true},outputs:{image:'keyframe/frames/00000.png'}};
 await fs.writeFile(path.join(jobRoot,'result.json'),JSON.stringify(receipt));
}
async function fixture(t,overrides={}){
 const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'vyrealm-original-test-')),jobsDir=path.join(dataDir,'jobs'),mediaDir=path.join(dataDir,'media');await fs.mkdir(jobsDir);await fs.mkdir(mediaDir);const db=new DatabaseSync(path.join(dataDir,'vyrelum.sqlite'));
 db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,revision INTEGER,document TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE project_revisions(project_id TEXT,revision INTEGER,document TEXT,created_at TEXT,PRIMARY KEY(project_id,revision));CREATE TABLE assets(id TEXT PRIMARY KEY,project_id TEXT,document TEXT,path TEXT,created_at TEXT);CREATE TABLE jobs(id TEXT PRIMARY KEY,project_id TEXT,revision INTEGER,type TEXT,status TEXT,progress REAL,stage TEXT,input TEXT,output TEXT,error TEXT,attempts INTEGER DEFAULT 0,created_at TEXT,updated_at TEXT)');
 const original={name:'Original film',brief:'Preserved earlier brief',timeline:[],latestOutput:{videoAssetId:'retained-history'}};db.prepare('INSERT INTO projects VALUES(?,?,?,?,?)').run('project-1',1,JSON.stringify(original),'old','old');db.prepare('INSERT INTO project_revisions VALUES(?,?,?,?)').run('project-1',1,JSON.stringify(original),'old');
 const events=[];const dependencies={preflight:async()=>({available:true}),acquireLease:async()=>{events.push('lease');const release=async()=>events.push('released');release.registerChild=async()=>{};return release;},startWorker:async args=>{events.push(args.kind);return{pid:process.pid,completion:imageFixture(args).then(()=>({exitCode:0})),cancel:async()=>{}};},cancelProvider:async()=>{},...overrides};
 const service=await createOriginalGenerationService({db,dataDir,jobsDir,mediaDir,root,dependencies});t.after(async()=>{await service.close();db.close();assert.equal(path.dirname(dataDir),path.resolve(os.tmpdir()));await fs.rm(dataDir,{recursive:true,force:true});});return{service,db,jobsDir,mediaDir,dataDir,events,original};
}
async function terminal(service,kind='keyframe'){for(let i=0;i<(kind==='motion'?12000:500);i++){const s=await service.state('project-1'),j=kind==='motion'?s.motionJob:s.keyframeJob;if(j&&!['queued','running','validating','cancelling'].includes(j.status))return s;await new Promise(r=>setTimeout(r,10));}assert.fail('job did not settle');}
const reviewInput=s=>({projectId:'project-1',expectedRevision:s.project.revision,jobId:s.keyframeJob.id,expectedOutputHash:s.keyframeJob.output.provenance.outputHash,verdict:'passed',notes:'Isolated CPU fixture only; checks test the ownership and review boundary, not cinematic quality.'});

test('arbitrary original brief keeps fixed qualified profile and rejects injected paths or stale controls',()=>{
 const parsed=validateOriginalRequest(input);assert.equal(parsed.brief,brief);assert.equal(parsed.seed,90820261);
 for(const extra of [{width:512},{frames:1000},{referencePath:'C:/external.png'},{provider:'cloud'},{expectedRevision:0}])assert.throws(()=>validateOriginalRequest({...input,...extra}));
});
test('motion preflight checks image-input node and reports its actual 121-frame profile',async t=>{
 const f=await fixture(t),nodes=[...new Set(Object.values(wanWorkflow({frames:1,prefix:'vyrealm/preflight/keyframe'})).map(n=>n.class_type))];const health={available:true,nodes,installedModels:{models:Object.values(WAN_MODELS)},system:{devices:[{type:'cuda',name:'Isolated metadata fixture',vram_total:6*1024**3}]}};const provider={health_check:async()=>health};
 await assert.rejects(preflightOriginalGeneration({request:input,kind:'motion',jobsDir:f.jobsDir,dataDir:f.dataDir,provider}),{code:'ORIGINAL_PROVIDER_BLOCKED'});health.nodes.push('LoadImage');const result=await preflightOriginalGeneration({request:input,kind:'motion',jobsDir:f.jobsDir,dataDir:f.dataDir,provider});assert.equal(result.profile.frames,121);assert.equal(result.profile.durationSeconds,5);assert.ok(result.estimate.seconds.min>=1500);
});
test('LTX motion choice is bounded and preflight requires its exact installed models and tiled nodes',async t=>{
 const f=await fixture(t),request={projectId:'project-1',expectedRevision:1,keyframeJobId:'key',expectedOutputHash:'a'.repeat(64),reviewHash:'b'.repeat(64),brief:'Original steam curls upward',seed:8,motionEngine:'ltx-draft-512'};assert.equal(validateReviewedMotionRequest(request).motionEngine,'ltx-draft-512');for(const extra of [{motionEngine:'comparison-1024'},{motionEngine:'auto'},{width:1024},{tiledDecode:false}])assert.throws(()=>validateReviewedMotionRequest({...request,...extra}));assert.deepEqual(validateReviewedMotionRequest({...request,motionEngine:undefined}),{...request,motionEngine:undefined});
 const workflow=reviewedMotionWorkflow({request,imageName:'owned.png',prefix:'vyrealm/preflight/motion'}),health={available:true,nodes:[...new Set(Object.values(workflow).map(n=>n.class_type))],installedModels:{models:Object.values(LTX_MODELS)},system:{devices:[{type:'cuda',name:'Explicit isolated metadata fixture',vram_total:6*1024**3}]}},provider={health_check:async()=>health};assert.equal(workflow['9'].class_type,'VAEDecodeTiled');assert.equal(workflow['7'].inputs.width,512);assert.equal(workflow['14'].inputs.steps,8);
 const result=await preflightOriginalGeneration({request,kind:'motion',jobsDir:f.jobsDir,dataDir:f.dataDir,provider});assert.equal(result.profile.qualified,false);assert.equal(result.profile.height,288);assert.equal(result.estimate.sampleCount,1);assert.match(result.estimate.basis,/rejected/);health.installedModels.models=Object.values(WAN_MODELS);await assert.rejects(preflightOriginalGeneration({request,kind:'motion',jobsDir:f.jobsDir,dataDir:f.dataDir,provider}),{code:'ORIGINAL_PROVIDER_BLOCKED'});
});

test('LTX cancellation reconstructs only the exact owned tiled graph',async t=>{
 const f=await fixture(t),jobRoot=path.join(f.jobsDir,'ltx-owned');await fs.mkdir(path.join(jobRoot,'motion'),{recursive:true});const request={projectId:'project-1',expectedRevision:1,keyframeJobId:'key',expectedOutputHash:'a'.repeat(64),reviewHash:'b'.repeat(64),brief:'Original steam curls upward',seed:8,motionEngine:'ltx-draft-512'},namespace='vyrealm/00000000-0000-4000-8000-000000000003',workflow=reviewedMotionWorkflow({request,imageName:'owned.png',prefix:`${namespace}/motion`}),foreign=ltxWorkflow({prompt:request.brief,seed:8,imageName:'owned.png',prefix:`${namespace}/motion`,tiledDecode:false});await fs.writeFile(path.join(jobRoot,'motion-request.json'),JSON.stringify(request));await fs.writeFile(path.join(jobRoot,'generation-checkpoint.json'),JSON.stringify({namespace}));await fs.writeFile(path.join(jobRoot,'motion/workflow.json'),JSON.stringify(workflow));const cancelled=[],provider={baseUrl:'http://127.0.0.1:8188',fetch:async()=>Response.json({queue_running:[[0,'foreign',foreign]],queue_pending:[[1,'owned-ltx',workflow]]}),cancel:async id=>cancelled.push(id)};await cancelOriginalProviderPrompt({jobRoot,kind:'motion',provider});assert.deepEqual(cancelled,['owned-ltx']);await fs.writeFile(path.join(jobRoot,'motion/workflow.json'),JSON.stringify(foreign));await assert.rejects(cancelOriginalProviderPrompt({jobRoot,kind:'motion',provider}),{code:'ORIGINAL_CANCEL_OWNERSHIP'});assert.equal(cancelled.length,1);
});
test('new generic generation stops after one owned still and preserves film history',async t=>{
 const f=await fixture(t),started=await f.service.start(input);assert.equal(started.project.revision,2);const s=await terminal(f.service);
 assert.equal(s.keyframeJob.status,'review_required');assert.equal(s.keyframeJob.output.provenance.mediaKind,'image');assert.equal(s.motionJob,null);assert.deepEqual(f.events.filter(x=>['keyframe','motion'].includes(x)),['keyframe']);assert.deepEqual(s.project.latestOutput,f.original.latestOutput);assert.deepEqual(s.project.timeline,[]);assert.equal(s.project.brief,f.original.brief,'a shot direction must not overwrite the project brief');assert.equal(s.project.originalGeneration.brief,brief);assert.equal(started.project.brief,f.original.brief);assert.equal(started.project.originalGeneration.brief,brief);assert.equal(s.project.originalGeneration.keyframeJobId,started.job.id);
});
test('stale admission and a second in-flight start cannot create another job',async t=>{
 let unblock;const wait=new Promise(r=>unblock=r);const f=await fixture(t,{preflight:async()=>wait});await assert.rejects(f.service.start({...input,expectedRevision:9}),{code:'ORIGINAL_REVISION_CONFLICT'});const s=await f.service.start(input);await assert.rejects(f.service.start({...input,expectedRevision:s.project.revision}),{code:'ORIGINAL_BUSY'});unblock({available:true});await terminal(f.service);assert.equal(f.db.prepare('SELECT count(*) n FROM jobs').get().n,1);
});
test('animation requires exact passed image review; wrong hash and missing notes fail',async t=>{
 const f=await fixture(t);await f.service.start(input);const s=await terminal(f.service),r=reviewInput(s);
 await assert.rejects(f.service.animate({projectId:'project-1',expectedRevision:s.project.revision,keyframeJobId:s.keyframeJob.id,expectedOutputHash:r.expectedOutputHash}),{code:'ORIGINAL_REVIEW_REQUIRED'});
 await assert.rejects(f.service.review({...r,notes:''}));await assert.rejects(f.service.review({...r,expectedOutputHash:'0'.repeat(64)}));
 const approved=await f.service.review(r);assert.equal(approved.keyframeJob.status,'succeeded');assert.equal(approved.project.originalGeneration.status,'keyframe-approved');assert.equal(approved.motionJob,null);assert.equal(f.db.prepare('SELECT count(*) n FROM jobs').get().n,1);
});
test('rejected reference cannot be approved later or animated',async t=>{
 const f=await fixture(t);await f.service.start(input);const s=await terminal(f.service),r=reviewInput(s),rejected=await f.service.review({...r,verdict:'rejected'});
 await assert.rejects(f.service.review({...r,expectedRevision:rejected.project.revision}),{code:'ORIGINAL_REJECTED_REFERENCE'});await assert.rejects(f.service.animate({projectId:'project-1',expectedRevision:rejected.project.revision,keyframeJobId:s.keyframeJob.id,expectedOutputHash:r.expectedOutputHash}));
});
test('changed registered bytes, missing provider log and unrelated jobs are not local references',async t=>{
 const f=await fixture(t);await f.service.start(input);const s=await terminal(f.service),r=reviewInput(s),asset=f.db.prepare('SELECT * FROM assets').get();await fs.appendFile(asset.path,'changed');await assert.rejects(f.service.review(r),{code:'KEYFRAME_ASSET'});
 await fs.copyFile(path.join(f.jobsDir,s.keyframeJob.id,'keyframe/frames/00000.png'),asset.path);await fs.unlink(path.join(f.jobsDir,s.keyframeJob.id,'keyframe/provider.jsonl'));await assert.rejects(f.service.review(r));
 await assert.rejects(f.service.review({...r,jobId:'external-import'}),{code:'ORIGINAL_JOB_NOT_FOUND'});
});
test('retry retains a completed provider stage without repeating inference',async t=>{
 let calls=0;const f=await fixture(t,{startWorker:async args=>({completion:(async()=>{if(++calls===1){await imageFixture(args);return{exitCode:1,error:'Injected interruption after owned frame evidence'};}await produceLocalKeyframe({...args,provider:{id:'comfyui-local',generate_video:()=>assert.fail('must reuse stage'),fetch:()=>assert.fail('cached stage is offline')}});return{exitCode:0};})(),cancel:async()=>{}})});
 await f.service.start(input);const blocked=await terminal(f.service);assert.equal(blocked.keyframeJob.status,'blocked');const frame=path.join(f.jobsDir,blocked.keyframeJob.id,'keyframe/frames/00000.png'),before=sha(await fs.readFile(frame));
 await f.service.retry({projectId:'project-1',expectedRevision:blocked.project.revision,jobId:blocked.keyframeJob.id});const complete=await terminal(f.service);assert.equal(complete.keyframeJob.status,'review_required');assert.equal(complete.keyframeJob.id,blocked.keyframeJob.id);assert.equal(sha(await fs.readFile(frame)),before);assert.equal(complete.keyframeJob.attempts,2);
});
test('project edited while a still runs retains its image without applying or approving it',async t=>{
 let finish,ready;const wait=new Promise(r=>finish=r),seen=new Promise(r=>ready=r);const f=await fixture(t,{startWorker:async args=>({completion:(async()=>{await imageFixture(args);ready();await wait;return{exitCode:0};})(),cancel:async()=>finish()})});await f.service.start(input);await seen;
 const p=f.db.prepare('SELECT * FROM projects').get(),d=JSON.parse(p.document);d.userNote='Retain this new edit';f.db.prepare('UPDATE projects SET revision=revision+1,document=?').run(JSON.stringify(d));finish();const s=await terminal(f.service);assert.equal(s.keyframeJob.output.promoted,false);assert.equal(s.project.userNote,d.userNote);assert.equal(f.db.prepare('SELECT count(*) n FROM assets').get().n,1);await assert.rejects(f.service.review(reviewInput(s)),{code:'ORIGINAL_REVISION_CONFLICT'});
});
test('approval rechecks revision after asynchronous file verification',async t=>{
 let proceed,seen;const wait=new Promise(r=>proceed=r),ready=new Promise(r=>seen=r);const f=await fixture(t,{verifyOwned:async args=>{const result=await verifyOwnedGeneratedKeyframe(args);seen();await wait;return result;}});await f.service.start(input);const s=await terminal(f.service),pending=f.service.review(reviewInput(s));await ready;f.db.prepare('UPDATE projects SET revision=revision+1').run();proceed();await assert.rejects(pending,{code:'ORIGINAL_REVISION_CONFLICT'});assert.equal((await f.service.state('project-1')).keyframeJob.status,'review_required');
});
test('new revision at the GPU boundary blocks a worker before it can sample',async t=>{
 let proceed,seen;const wait=new Promise(r=>proceed=r),ready=new Promise(r=>seen=r);const f=await fixture(t,{acquireLease:async()=>{seen();await wait;return async()=>{};},startWorker:()=>assert.fail('stale generation must not start')});await f.service.start(input);await ready;f.db.prepare('UPDATE projects SET revision=revision+1').run();proceed();const s=await terminal(f.service);assert.equal(s.keyframeJob.status,'blocked');assert.match(s.keyframeJob.error,/ORIGINAL_REVISION_CONFLICT/);
});
test('cancel during preflight releases ownership and starts no worker',async t=>{
 let seen;const ready=new Promise(r=>seen=r);const f=await fixture(t,{preflight:async()=>{seen();return new Promise(()=>{});},startWorker:()=>assert.fail('cancelled worker')});const s=await f.service.start(input);await ready;await f.service.cancel(s.job.id);assert.equal((await terminal(f.service)).keyframeJob.status,'cancelled');assert.equal(f.events.filter(e=>e==='released').length,1);
});
test('restart recovery marks only its own interrupted jobs and does not auto-generate',async t=>{
 const f=await fixture(t);await f.service.close();const insert=f.db.prepare('INSERT INTO jobs(id,project_id,type,status,input,created_at,updated_at) VALUES(?,?,?,?,?,?,?)');insert.run('own','project-1','generation-shot','running',JSON.stringify({serviceOwner:'original-neural-service-v1',stageKind:'motion'}),'now','now');insert.run('foreign','project-1','generation-shot','running','{}','now','now');const cancelled=[];const recovered=await createOriginalGenerationService({...f,root,dependencies:{cancelProvider:async id=>cancelled.push(id),startWorker:()=>assert.fail('restart must not infer')}});assert.deepEqual(cancelled,['own']);assert.equal(f.db.prepare('SELECT status FROM jobs WHERE id=?').get('own').status,'failed');assert.equal(f.db.prepare('SELECT status FROM jobs WHERE id=?').get('foreign').status,'running');await recovered.close();
});
test('cancellation targets only the exact owned workflow',async t=>{
 const f=await fixture(t);await f.service.start(input);const s=await terminal(f.service),jobRoot=path.join(f.jobsDir,s.keyframeJob.id),request=JSON.parse(await fs.readFile(path.join(jobRoot,'request.json'),'utf8')),workflow=wanWorkflow({...request,frames:1,prefix:`vyrealm/${s.keyframeJob.id}/keyframe`}),foreign=wanWorkflow({...request,frames:1,prefix:'vyrealm/other/keyframe'}),cancelled=[];
 await cancelOriginalProviderPrompt({jobRoot,kind:'keyframe',provider:{baseUrl:'http://127.0.0.1:8188',fetch:async()=>Response.json({queue_running:[[0,'foreign',foreign]],queue_pending:[[1,'owned',workflow]]}),cancel:async id=>cancelled.push(id)}});assert.deepEqual(cancelled,['owned']);
});
test('a second application instance never interrupts a live owner process',async t=>{
 const f=await fixture(t);await f.service.close();f.db.prepare('INSERT INTO jobs(id,project_id,type,status,input,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run('live-owner','project-1','generation-shot','running',JSON.stringify({serviceOwner:'original-neural-service-v1',ownerPid:process.pid,stageKind:'motion'}),'now','now');
 const other=await createOriginalGenerationService({...f,root,dependencies:{cancelProvider:()=>assert.fail('must not stop live application')}});assert.equal(f.db.prepare('SELECT status FROM jobs WHERE id=?').get('live-owner').status,'running');await assert.rejects(other.cancel('live-owner'),{code:'ORIGINAL_OTHER_PROCESS'});await other.close();
});
test('a receipt relabelled as imported is blocked before any generated asset registration',async t=>{
 const f=await fixture(t,{startWorker:async args=>({completion:(async()=>{await imageFixture(args);const file=path.join(args.jobRoot,'result.json'),receipt=JSON.parse(await fs.readFile(file));receipt.provenance.generationStatus='imported';await fs.writeFile(file,JSON.stringify(receipt));return{exitCode:0};})(),cancel:async()=>{}})});await f.service.start(input);const s=await terminal(f.service);assert.equal(s.keyframeJob.status,'blocked');assert.match(s.keyframeJob.error,/KEYFRAME_RECEIPT/);assert.equal(f.db.prepare('SELECT count(*) n FROM assets').get().n,0);
});

for(const motionEngine of ['wan','ltx-draft-512'])test(`${motionEngine}: approved still animates through fake provider into real 5s MP4 with independent delivery provenance`,async t=>{
 const dimensions=motionEngine==='ltx-draft-512'?{width:512,height:288}:{width:1024,height:576};
 let f,submissions=0,uploaded;const histories=new Map(),frames=new Map();
 const provider={id:'comfyui-local',baseUrl:'http://127.0.0.1:8188',upload_inputs:async values=>{uploaded=values[0].data;return{uploaded:[{name:'owned-reference.png',subfolder:'',type:'input'}]};},generate_video:async({workflow})=>{
  submissions++;assert.equal(workflow['7'].inputs.length,121);assert.ok(workflow['11'],'motion must use the approved input');const directory=path.join(f.dataDir,'fixture-motion');await fs.mkdir(directory);await exec(path.join(root,'workers/tools/ffmpeg.exe'),['-v','error','-f','lavfi','-i',`testsrc2=s=${dimensions.width}x${dimensions.height}:r=24`,'-frames:v','121','-threads','1',path.join(directory,'%05d.png')],{windowsHide:true,timeout:30000});
  const prefix=workflow['10'].inputs.filename_prefix,subfolder=path.posix.dirname(prefix),name=path.posix.basename(prefix),descriptors=[];for(let i=0;i<121;i++){const filename=`${name}_${String(i).padStart(5,'0')}.png`;frames.set(filename,await fs.readFile(path.join(directory,`${String(i+1).padStart(5,'0')}.png`)));descriptors.push({filename,subfolder,type:'output'});}const promptId='isolated-motion-fixture';histories.set(promptId,{prompt:[0,promptId,workflow],status:{completed:true,status_str:'success'},outputs:{'10':{images:descriptors}}});return{promptId};
 },fetch:async url=>{const u=new URL(url);if(u.pathname==='/queue')return Response.json({queue_running:[],queue_pending:[]});if(u.pathname.startsWith('/history/')){const id=u.pathname.split('/').at(-1);return Response.json({[id]:histories.get(id)});}if(u.pathname==='/view')return new Response(u.searchParams.get('type')==='input'?uploaded:frames.get(u.searchParams.get('filename')));assert.fail('unexpected fake request');}};
 f=await fixture(t,{startWorker:async args=>({pid:process.pid,completion:(async()=>{if(args.kind==='keyframe')await imageFixture(args);else await produceReviewedKeyframeMotion({...args,db:f.db,jobsDir:f.jobsDir,mediaDir:f.mediaDir,provider});return{exitCode:0};})().catch(e=>({exitCode:1,error:e.stack})),cancel:async()=>{}})});
 await f.service.start(input);const still=await terminal(f.service),approved=await f.service.review(reviewInput(still)),motionBrief='Steam coils slowly upward; rain beads slide down the window. Keep the camera nearly still.';await f.service.animate({projectId:'project-1',expectedRevision:approved.project.revision,keyframeJobId:still.keyframeJob.id,expectedOutputHash:still.keyframeJob.output.provenance.outputHash,brief:motionBrief,motionEngine});const s=await terminal(f.service,'motion');
 assert.equal(s.project.brief,f.original.brief);assert.equal(s.project.originalGeneration.brief,brief);assert.equal(s.project.originalGeneration.motionBrief,motionBrief);assert.equal(s.project.originalGeneration.motionEngine,motionEngine);assert.equal(s.motionJob.motionEngine,motionEngine);assert.equal(s.motionJob.output.provenance.prompt,motionBrief);
 assert.equal(s.motionJob.status,'review_required',s.motionJob.error);assert.equal(submissions,1);assert.equal(s.project.latestOutput.status,'review_required');assert.equal(s.project.timeline.length,1);assert.equal(s.motionJob.output.provenance.durationSeconds,5);assert.equal(s.motionJob.output.provenance.frameCount,120);assert.deepEqual(s.motionJob.output.provenance.resolution,dimensions);assert.deepEqual(s.motionJob.output.provenance.deliveryResolution,{width:1920,height:1080});assert.notEqual(s.motionJob.output.provenance.outputHash,s.motionJob.output.provenance.sourceHash);assert.equal(s.motionJob.output.keyframeReview.sourceJobId,still.keyframeJob.id);
 const row=f.db.prepare('SELECT * FROM jobs WHERE id=?').get(s.motionJob.id),request=JSON.parse(row.input).request,jobRoot=path.join(f.jobsDir,s.motionJob.id);
 const reviewTarget=await verifyReviewTarget({db:f.db,jobsDir:f.jobsDir,mediaDir:f.mediaDir,job:row,output:JSON.parse(row.output),expectedOutputHash:s.motionJob.output.provenance.outputHash});assert.equal(reviewTarget.hash,s.motionJob.output.provenance.outputHash,'the existing video-review route accepts this exact owned delivery');
 const uploadPath=path.join(jobRoot,'input-upload.json'),upload=JSON.parse(await fs.readFile(uploadPath));await fs.writeFile(uploadPath,JSON.stringify({...upload,imageName:'unrelated.png'}));await assert.rejects(verifyReviewedMotionEvidence({jobRoot,request,db:f.db,jobsDir:f.jobsDir,mediaDir:f.mediaDir}),{code:'ORIGINAL_INPUT_BINDING'});await fs.writeFile(uploadPath,JSON.stringify(upload));
 await fs.appendFile(path.join(jobRoot,'reference.png'),'tamper');await assert.rejects(verifyReviewedMotionEvidence({jobRoot,request,db:f.db,jobsDir:f.jobsDir,mediaDir:f.mediaDir}),{code:'ORIGINAL_REFERENCE_CHANGED'});
});
