import test from 'node:test';import assert from 'node:assert/strict';import {originalGenerationStage,createOriginalGenerationPanel,originalMotionChoices} from '../original-generation.js';
const browserLaunchOptions=()=>({headless:true,timeout:15000,...(process.env.VYREALM_TEST_BROWSER_EXECUTABLE?{executablePath:process.env.VYREALM_TEST_BROWSER_EXECUTABLE}:{})});
function browserFixture(t,cleanupFiles=async()=>{}){
 const fixture={browser:null,server:null,pending:[]};
 t.after(async()=>{fixture.pending.splice(0).forEach(res=>res.destroy());try{await fixture.browser?.close();}finally{fixture.server?.closeAllConnections?.();if(fixture.server?.listening)await new Promise(resolve=>fixture.server.close(resolve));await cleanupFiles();}});
 return fixture;
}
const still={id:'key',stageKind:'keyframe',status:'review_required',output:{assets:{image:'asset'},provenance:{outputHash:'a'.repeat(64)}}};
test('a generated frame requires review and has no animation action until approved',()=>{const html=originalGenerationStage({keyframeJob:still,job:still});assert.match(html,/originalApprove/);assert.match(html,/originalReviewNotes/);assert.doesNotMatch(html,/id="originalAnimate"/);});
test('exact frame approval exposes animation but not a video claim',()=>{const approved={...still,status:'succeeded',output:{...still.output,review:{verdict:'passed'}}},html=originalGenerationStage({keyframeJob:approved,job:approved});assert.match(html,/id="originalAnimate"/);assert.doesNotMatch(html,/<video/);});
test('completed motion shows the actual delivery and manual review action',()=>{const motion={id:'motion',stageKind:'motion',status:'review_required',output:{assets:{video:'clip'}}},html=originalGenerationStage({keyframeJob:still,motionJob:motion,job:motion});assert.match(html,/src="\/media\/clip"/);assert.match(html,/originalReviewExport/);assert.match(html,/resized from/);assert.doesNotMatch(html,/native 1080p/);});
test('errors and saved shot prompts remain escaped and new projects have no fake media',()=>{let html=originalGenerationStage({job:{id:'bad',status:'failed',error:'<script>broken</script>',attempts:1}});assert.match(html,/&lt;script&gt;broken/);assert.doesNotMatch(html,/<script>/);html=createOriginalGenerationPanel({store:{project:{id:'p',originalGeneration:{brief:'<img src=x>'}}}}).html();assert.match(html,/&lt;img src=x&gt;/);assert.doesNotMatch(html,/<img/);});
test('uploaded edit instructions never silently become an original image prompt',()=>{const html=createOriginalGenerationPanel({store:{project:{id:'p',brief:'Trim 6–12 seconds, fit landscape, no captions',timeline:[{assetId:'footage'}]}}}).html();assert.match(html,/id="originalUseProjectBrief"/);assert.doesNotMatch(html,/Trim 6–12/);assert.match(html,/<textarea id="originalBrief"[^>]*><\/textarea>/);});
test('experimental motion selection is explicit and displayed only after still approval',()=>{const unreviewed=originalGenerationStage({keyframeJob:still,job:still});assert.doesNotMatch(unreviewed,/originalMotionEngine/);const approved={...still,status:'succeeded',output:{...still.output,review:{verdict:'passed'}}},html=originalGenerationStage({keyframeJob:approved,job:approved});assert.match(html,/<option value="wan">/);assert.match(html,/value="ltx-draft-512">LTX draft · 288p · Experimental/);assert.match(originalMotionChoices['ltx-draft-512'].note,/72\.648/);assert.match(originalMotionChoices['ltx-draft-512'].note,/rejected.*hand/);assert.match(originalMotionChoices['ltx-draft-512'].note,/Custom model-weight license/);});
test('LTX delivery shows its recorded 288p source, never the Wan source resolution',()=>{const motion={id:'motion',stageKind:'motion',motionEngine:'ltx-draft-512',status:'review_required',output:{assets:{video:'clip'},provenance:{resolution:{width:512,height:288}}}},html=originalGenerationStage({keyframeJob:still,motionJob:motion,job:motion});assert.match(html,/512×288 source/);assert.match(html,/Experimental LTX draft/);assert.doesNotMatch(html,/1024×576/);assert.match(html,/Review motion/);});
test('motion preview uses the approved single image and keeps the contact sheet separate',()=>{const approved={...still,status:'succeeded',output:{...still.output,review:{verdict:'passed'}}},motion={id:'motion',stageKind:'motion',status:'review_required',output:{assets:{video:'clip',poster:'wide-sheet'}}},html=originalGenerationStage({keyframeJob:approved,motionJob:motion,job:motion});assert.match(html,/poster="\/media\/asset"/);assert.doesNotMatch(html,/poster="\/media\/wide-sheet"/);assert.match(html,/data-original-contact-sheet href="\/media\/wide-sheet"/);assert.match(html,/width="1920" height="1080"/);const unreviewed=originalGenerationStage({keyframeJob:still,motionJob:motion,job:motion});assert.doesNotMatch(unreviewed,/<video[^>]*poster=/);});
test('real MP4 preview remains 16:9 before and after metadata at desktop/mobile and plays',{timeout:45000},async t=>{
 const {chromium}=await import('@playwright/test'),{createServer}=await import('node:http'),fs=await import('node:fs/promises'),path=await import('node:path'),{tmpdir}=await import('node:os'),{execFile}=await import('node:child_process'),{promisify}=await import('node:util');const temp=await fs.mkdtemp(path.join(tmpdir(),'vyrealm-poster-test-')),exec=promisify(execFile),ffmpeg=new URL('../workers/tools/ffmpeg.exe',import.meta.url).pathname.replace(/^\/(?=[A-Za-z]:)/,'');
 const fixture=browserFixture(t,async()=>{assert.equal(path.dirname(temp),path.resolve(tmpdir()));await fs.rm(temp,{recursive:true,force:true});});
 await exec(ffmpeg,['-v','error','-f','lavfi','-i','testsrc2=s=320x180:r=24','-t','5','-c:v','libx264','-threads','1','-pix_fmt','yuv420p','-movflags','+faststart',path.join(temp,'clip.mp4')],{windowsHide:true,timeout:15000});await exec(ffmpeg,['-v','error','-i',path.join(temp,'clip.mp4'),'-frames:v','1','-threads','1',path.join(temp,'keyframe.png')],{windowsHide:true,timeout:15000});await exec(ffmpeg,['-v','error','-i',path.join(temp,'clip.mp4'),'-vf','fps=1,tile=5x1','-frames:v','1','-threads','1',path.join(temp,'sheet.png')],{windowsHide:true,timeout:15000});
 const [clip,keyframe,sheet,css]=await Promise.all([fs.readFile(path.join(temp,'clip.mp4')),fs.readFile(path.join(temp,'keyframe.png')),fs.readFile(path.join(temp,'sheet.png')),fs.readFile(new URL('../styles.css',import.meta.url))]);const approved={...still,status:'succeeded',output:{...still.output,assets:{image:'keyframe'},review:{verdict:'passed'}}},motion={id:'motion',stageKind:'motion',status:'review_required',output:{assets:{video:'clip',poster:'sheet'}}};let hold=true,pending=fixture.pending;
 const videoResponse=res=>{res.writeHead(200,{'content-type':'video/mp4','content-length':clip.length});res.end(clip);};const server=fixture.server=createServer((req,res)=>{if(req.url==='/styles.css'){res.setHeader('content-type','text/css');return res.end(css);}if(req.url==='/media/keyframe'||req.url==='/media/sheet'){res.setHeader('content-type','image/png');return res.end(req.url.endsWith('keyframe')?keyframe:sheet);}if(req.url==='/media/clip'){if(hold)pending.push(res);else videoResponse(res);return;}res.setHeader('content-type','text/html');res.end(`<!doctype html><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/styles.css"><main style="width:100%;max-width:1000px;padding:16px">${originalGenerationStage({keyframeJob:approved,motionJob:motion,job:motion})}</main>`);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=fixture.browser=await chromium.launch(browserLaunchOptions());
 const evidence=[],out=path.resolve('work/original-preview-layout-proof');await fs.mkdir(out,{recursive:true});for(const width of [1440,390]){hold=true;const page=await browser.newPage({viewport:{width,height:1000}});await page.goto(`http://127.0.0.1:${server.address().port}`,{waitUntil:'domcontentloaded'});const video=page.locator('video.original-preview');await video.waitFor();assert.equal(await video.getAttribute('poster'),'/media/keyframe');assert.equal(await video.evaluate(v=>v.readyState),0);const measure=()=>video.evaluate(v=>{const r=v.getBoundingClientRect();return{width:r.width,height:r.height,ratio:r.width/r.height,readyState:v.readyState};});const before=await measure();assert.ok(Math.abs(before.ratio-16/9)<.01,JSON.stringify(before));await page.screenshot({path:path.join(out,`${width}-before-metadata.png`)});hold=false;pending.splice(0).forEach(videoResponse);await page.waitForFunction(()=>document.querySelector('video').readyState>=1);const after=await measure();assert.ok(Math.abs(after.ratio-16/9)<.01);assert.ok(Math.abs(before.height-after.height)<1);await video.evaluate(async v=>{v.muted=true;await v.play();});await page.waitForFunction(()=>document.querySelector('video').currentTime>.15);await video.evaluate(v=>v.pause());await page.screenshot({path:path.join(out,`${width}-playing.png`)});await page.locator('.original-evidence summary').click();const popupPromise=page.waitForEvent('popup');await page.locator('[data-original-contact-sheet]').click();const popup=await popupPromise;await popup.waitForLoadState();assert.ok(await popup.locator('img').evaluate(i=>i.naturalWidth/i.naturalHeight>8));await popup.close();evidence.push({viewport:width,before,after,poster:'approved single keyframe',contactSheet:'separate real five-wide PNG',playback:'currentTime advanced'});await page.close();}await fs.writeFile(path.join(out,'evidence.json'),JSON.stringify({scope:'Actual CPU-generated MP4/image fixtures; no canonical mutation or inference',evidence},null,2));
});
test('browser submits an explicit LTX selection with the exact current review hash and edited motion brief',{timeout:30000},async t=>{
 const {chromium}=await import('@playwright/test'),{createServer}=await import('node:http'),{readFile}=await import('node:fs/promises');const script=await readFile(new URL('../original-generation.js',import.meta.url));const fixture=browserFixture(t);
 const server=fixture.server=createServer((req,res)=>{if(req.url==='/original-generation.js'){res.setHeader('content-type','text/javascript');return res.end(script);}res.setHeader('content-type','text/html');res.end(`<!doctype html><main id="root"></main><script type="module">import{createOriginalGenerationPanel}from'/original-generation.js';window.store={project:{id:'fixture-project',revision:5,brief:'Separate project brief',originalGeneration:{brief:'Original ceramic cup'}},dirty:false};window.requests=[];const still={id:'fixture-key',stageKind:'keyframe',status:'succeeded',output:{provenance:{outputHash:'${'a'.repeat(64)}'},review:{verdict:'passed'}}};let state={project:store.project,keyframeJob:still,job:still};window.panel=createOriginalGenerationPanel({store,api:async(path,options)=>{if(options){requests.push({path,body:JSON.parse(options.body)});state={...state,project:{...store.project,revision:6},motionJob:{id:'fixture-motion',stageKind:'motion',motionEngine:'ltx-draft-512',status:'queued'},job:{id:'fixture-motion',stageKind:'motion',status:'queued'}};}return state;},refresh:async()=>{},saveProject:async()=>{},onNavigate:()=>{}});document.querySelector('#root').innerHTML=panel.html();panel.bind();</script>`);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=fixture.browser=await chromium.launch(browserLaunchOptions());const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);await page.locator('#originalMotionEngine').waitFor();assert.equal(await page.locator('#originalMotionEngine').inputValue(),'wan');await page.locator('#originalMotionEngine').selectOption('ltx-draft-512');assert.match(await page.locator('#originalMotionEngineNote').innerText(),/rejected.*hand/);await page.locator('#originalMotionBrief').fill('Only steam moves; the cup and camera stay still.');await page.locator('#originalAnimate').click();await page.waitForFunction(()=>window.requests.length===1);const request=(await page.evaluate(()=>window.requests))[0];assert.equal(request.path,'/original-generation/fixture-key/animate');assert.deepEqual(request.body,{projectId:'fixture-project',expectedRevision:5,expectedOutputHash:'a'.repeat(64),brief:'Only steam moves; the cup and camera stay still.',motionEngine:'ltx-draft-512'});assert.equal(await page.locator('video').count(),0,'queue admission must not invent a generated clip');assert.equal(await page.evaluate(()=>store.project.brief),'Separate project brief');await page.evaluate(()=>panel.dispose());
});
