import { randomUUID } from 'node:crypto';
import { FORMATS, PLATFORM_SPECS, CAPTION_STYLES, buildProductionPlan } from './format-library.mjs';

const fail=message=>{throw Object.assign(new Error(message),{code:'RECIPE_DRAFT_INVALID'});};
const methods=Object.freeze({
 'local-media':['uploaded-local-media'],
 'local-generation':['qualified-local-generation'],
 mixed:['uploaded-local-media','qualified-local-generation'],
});
const sourceHints=Object.freeze({
 product:'Original product photography or footage showing the real item and its details.',
 screen:'Your own screen recording with readable interface text and permission to show its content.',
 'talking-head':'Your own speaker recording with usable dialogue audio and permission to use their appearance.',
 'anime-hero':'An original, detailed character reference with consistent face, hair and wardrobe.',
 'anime-action':'Original character action footage or qualified local motion generation with consistent references.',
 establish:'A detailed environment with depth, coherent lighting and suitable framing for this canvas.',
 diagram:'An original diagram or permitted illustration whose labels remain readable at delivery size.',
});

/** @typedef {{formatId:string,platform:string,name:string,brief:string,sourceMode:'local-media'|'local-generation'|'mixed',captionsEnabled?:boolean}} RecipeDraftInput */
/** Build an unrendered draft from a fixed internal recipe; never fetches media or starts inference. */
export function prepareRecipeProject(input={}) {
 if(!input||typeof input!=='object'||Array.isArray(input))fail('Recipe settings must be an object');
 const keys=new Set(['formatId','platform','name','brief','sourceMode','captionsEnabled']);
 if(Object.keys(input).some(key=>!keys.has(key)))fail('Recipe drafts accept only a format, platform, original brief, name, source intent and caption preference');
 if(!Object.hasOwn(FORMATS,input.formatId||''))fail('Choose an available production recipe');
 if(!Object.hasOwn(PLATFORM_SPECS,input.platform||'')||!FORMATS[input.formatId].platforms.includes(input.platform))fail('This recipe does not support the selected platform');
 if(typeof input.name!=='string'||!input.name.trim()||input.name.length>140)fail('Use a project name of 1–140 characters');
 if(typeof input.brief!=='string'||!input.brief.trim()||input.brief.length>6000)fail('Describe your original production in 1–6000 characters');
 const sourceMode=input.sourceMode||'local-media';if(!Object.hasOwn(methods,sourceMode))fail('Choose local media, qualified local generation, or both');
 if(input.captionsEnabled!==undefined&&typeof input.captionsEnabled!=='boolean')fail('Caption preference must be true or false');
 const plan=buildProductionPlan({formatId:input.formatId,platform:input.platform,brief:input.brief.trim()});
 const captionsEnabled=input.captionsEnabled??plan.captionStyle.id!=='none';
 if(!captionsEnabled)plan.captionStyle={id:'none',...CAPTION_STYLES.none};
 else if(plan.captionStyle.id==='none')plan.captionStyle={id:'minimal-lower',...CAPTION_STYLES['minimal-lower']};
 const sourceRequirements=plan.missingShotRoles.map(role=>({role,status:'missing',acceptedMethods:[...methods[sourceMode]],beatIndexes:plan.timeline.filter(beat=>beat.shotRole===role).map(beat=>beat.index),instruction:sourceHints[role]||'Provide original or licensed local media with a clear subject, environment, lighting and the action called for in the brief.'}));
 const productionPlan={...plan,status:'planned',renderable:false,sourceMode,sourceRequirements,audioRequirements:{status:'missing',profile:plan.audio.id,instruction:'Provide usable local speech, music or sound design for the recipe. Audio is not generated by saving this draft.'},providerQualification:sourceMode==='local-media'?'not-requested':'required-before-generation',generationRequested:false,importRequested:false};
 return {name:input.name.trim(),brief:input.brief.trim(),mode:plan.niche==='product'?'product':'cinematic',demo:false,creationSource:'format-recipe',recipeId:plan.formatId,platform:plan.platform,durationSeconds:plan.durationSeconds,settings:{...plan.canvas},captionsEnabled,productionPlan,timeline:[],assets:[],scene:{objects:[],lights:[],camera:{position:[0,0,3],target:[0,0,0]}},latestOutput:null};
}

/** Save a new project and revision atomically in the existing canonical SQLite store. */
export function createRecipeProject({db,input}) {
 const document=prepareRecipeProject(input),id=randomUUID(),createdAt=new Date().toISOString(),serialized=JSON.stringify(document);
 db.exec('BEGIN IMMEDIATE');
 try{
  db.prepare('INSERT INTO projects (id,revision,document,created_at,updated_at) VALUES (?,?,?,?,?)').run(id,1,serialized,createdAt,createdAt);
  db.prepare('INSERT INTO project_revisions (project_id,revision,document,created_at) VALUES (?,?,?,?)').run(id,1,serialized,createdAt);
  db.exec('COMMIT');
 }catch(error){try{db.exec('ROLLBACK');}catch{}throw error;}
 return {...document,id,revision:1,createdAt,updatedAt:createdAt};
}
