import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readConversation,sendConversation,saveCharacter,generateStudioReply,createStudioSession,listStudioSessions } from './studio-conversation.mjs';
function fixture(t){const db=new DatabaseSync(':memory:');t.after(()=>db.close());db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,revision INTEGER,document TEXT,created_at TEXT,updated_at TEXT); CREATE TABLE project_revisions(project_id TEXT,revision INTEGER,document TEXT,created_at TEXT,PRIMARY KEY(project_id,revision)); CREATE TABLE jobs(id TEXT,project_id TEXT,type TEXT,status TEXT,stage TEXT,output TEXT,updated_at TEXT); CREATE TABLE assets(id TEXT,project_id TEXT,document TEXT);');for(const id of ['film','other']){const doc=JSON.stringify({name:id,brief:'An original story',timeline:[],latestOutput:{status:'rejected'}});db.prepare('INSERT INTO projects VALUES(?,?,?,?,?)').run(id,1,doc,'today','today');db.prepare('INSERT INTO project_revisions VALUES(?,?,?,?)').run(id,1,doc,'today');}db.prepare('INSERT INTO assets VALUES(?,?,?)').run('owned','film','{"kind":"image"}');db.prepare('INSERT INTO assets VALUES(?,?,?)').run('foreign','other','{"kind":"image"}');return db;}
const input={id:'unique-turn-001',expectedRevision:1,text:'Develop the main character',useLocalModel:false};
test('separate conversations retain project context but do not mix messages or cross projects',async t=>{const db=fixture(t);const session=createStudioSession(db,'film','Second idea');await sendConversation({db,projectId:'film',input});await sendConversation({db,projectId:'film',input:{...input,id:'unique-turn-002',sessionId:session.id,text:'A separate direction'}});assert.equal(readConversation(db,'film').length,1);assert.equal(readConversation(db,'film',session.id)[0].text,'A separate direction');assert.equal(listStudioSessions(db,'film').length,2);assert.throws(()=>readConversation(db,'other',session.id),{code:'CHAT_SESSION_MISSING'});assert.equal(db.prepare('SELECT revision FROM projects WHERE id=?').get('film').revision,1);});
test('conversation persists without claiming generation or changing project/history',async t=>{const db=fixture(t);const before=db.prepare('SELECT * FROM projects').all();const turn=await sendConversation({db,projectId:'film',input});assert.equal(turn.status,'answered');assert.equal(turn.response.source,'local-workflow-guide');assert.match(turn.response.text,/No media job was started/);assert.deepEqual(readConversation(db,'film'),[turn]);assert.deepEqual(db.prepare('SELECT * FROM projects').all(),before);assert.equal(db.prepare('SELECT count(*) AS n FROM jobs').get().n,0);});
test('same turn retries are idempotent; differing input and stale revisions fail',async t=>{const db=fixture(t);let calls=0;const reply=async()=>{calls++;return {text:'Draft',actions:['plan']};};const a=await sendConversation({db,projectId:'film',input,reply});const b=await sendConversation({db,projectId:'film',input,reply});assert.deepEqual(a,b);assert.equal(calls,1);await assert.rejects(sendConversation({db,projectId:'film',input:{...input,text:'different'}}),{code:'CHAT_ID_CONFLICT'});await assert.rejects(sendConversation({db,projectId:'film',input:{...input,id:'unique-turn-002',expectedRevision:2}}),{code:'CHAT_REVISION_CONFLICT'});});
test('character edits version project and retain completed outputs; foreign/rejected references fail closed',t=>{const db=fixture(t);const request={expectedRevision:1,name:'Archer',description:'Tied-back hair, bow, ivory drape',referenceAssetId:'owned'};const result=saveCharacter({db,projectId:'film',input:request});assert.equal(result.revision,2);assert.equal(result.latestOutput.status,'rejected');assert.equal(result.characters[0].status,'direction-only');assert.equal(db.prepare('SELECT count(*) AS n FROM project_revisions WHERE project_id=?').get('film').n,2);assert.throws(()=>saveCharacter({db,projectId:'film',input:{...request,expectedRevision:2,referenceAssetId:'foreign'}}),{code:'CHARACTER_REFERENCE_INVALID'});db.prepare('INSERT INTO jobs VALUES(?,?,?,?,?,?,?)').run('bad','film','generation-test','rejected','review rejected','{"assets":{"poster":"owned"}}','today');assert.throws(()=>saveCharacter({db,projectId:'film',input:{...request,expectedRevision:2}}),{code:'CHARACTER_REFERENCE_REJECTED'});assert.equal(db.prepare('SELECT revision FROM projects WHERE id=?').get('film').revision,2);});
test('local chat rejects remote endpoint and invalid model actions without side effects',async()=>{let calls=0;const result=await generateStudioReply({text:'Plan',context:{name:'Film',timelineClips:0,outputStatus:'none'},endpoint:'https://outside.example',fetchImpl:async()=>{calls++;}});assert.equal(calls,0);assert.equal(result.source,'local-workflow-guide');const payloads=[];const fetchImpl=async(url,options)=>{payloads.push(options);return {ok:true,json:async()=>url.endsWith('/tags')?{models:[{name:'qwen3:4b-instruct',digest:'abc'}]}:{response:'{"text":"Done","actions":["run_shell"]}'}};};const rejected=await generateStudioReply({text:'Plan',context:{name:'Film',timelineClips:0,outputStatus:'none'},fetchImpl});assert.equal(rejected.source,'local-workflow-guide');assert.match(rejected.diagnostic,/invalid response/);const body=JSON.parse(payloads[1].body);assert.equal(body.options.num_gpu,0);assert.equal(body.keep_alive,0);assert.equal(body.stream,false);});
test('model response is a draft with measured model provenance, never execution',async()=>{const fetchImpl=async url=>({ok:true,json:async()=>url.endsWith('/tags')?{models:[{name:'qwen3:4b-instruct',digest:'abc'}]}:{response:'{"text":"Open on the wheel sinking into dust.","actions":["storyboard"]}'}});const r=await generateStudioReply({text:'Opening idea',context:{},fetchImpl});assert.equal(r.source,'ollama-local-draft');assert.equal(r.digest,'abc');assert.equal(r.execution,'suggestions-only');});
test('project changes during a response are disclosed against original revision',async t=>{const db=fixture(t);const turn=await sendConversation({db,projectId:'film',input,reply:async()=>{db.prepare('UPDATE projects SET revision=2 WHERE id=?').run('film');return {text:'Draft',actions:[]};}});assert.equal(turn.response.projectChanged,true);assert.equal(turn.response.basedOnRevision,1);});
