import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { createThumbnailService } from './thumbnail-service.mjs';
test('service persists real assets and a durable job; rejects stale revisions and foreign media', async t => {
  const jobsDir = await fs.mkdtemp(path.join(os.tmpdir(), 'vyrealm-thumbnail-service-')), db = new DatabaseSync(':memory:');
  t.after(async () => { db.close(); if (path.dirname(jobsDir) === path.resolve(os.tmpdir()) && path.basename(jobsDir).startsWith('vyrealm-thumbnail-service-')) await fs.rm(jobsDir, { recursive: true, force: true }); });
  db.exec('CREATE TABLE projects(id TEXT PRIMARY KEY,revision INTEGER,document TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE project_revisions(project_id TEXT,revision INTEGER,document TEXT,created_at TEXT);CREATE TABLE assets(id TEXT,project_id TEXT,document TEXT,path TEXT,created_at TEXT);CREATE TABLE jobs(id TEXT,project_id TEXT,revision INTEGER,type TEXT,status TEXT,progress REAL,stage TEXT,input TEXT,output TEXT,error TEXT,attempts INTEGER,created_at TEXT,updated_at TEXT);');
  db.prepare('INSERT INTO projects VALUES (?,?,?,?,?)').run('project-1', 1, JSON.stringify({ name: 'A quiet morning' }), '', '');
  const service = createThumbnailService({ db, jobsDir, root: fileURLToPath(new URL('..', import.meta.url)) });
  for (const input of [null, [], 'bad']) await assert.rejects(service.generate('project-1', input), { code: 'THUMBNAIL_REQUEST' });
  await assert.rejects(service.generate('project-1', { expectedRevision: 0, source: 'prompt' }), { code: 'THUMBNAIL_REVISION' });
  await assert.rejects(service.generate('project-1', { expectedRevision: 1, source: 'image', imageAssetId: 'foreign-asset' }), { code: 'THUMBNAIL_SOURCE' });
  await assert.rejects(service.generate('project-1', { expectedRevision: 1, source: 'prompt', videoPath: 'C:/anything' }), { code: 'THUMBNAIL_REQUEST' });
  const result = await service.handle({ method: 'POST', pathname: '/api/thumbnail/projects/project-1', body: { expectedRevision: 1, source: 'prompt', title: 'A quiet morning' } });
  assert.equal(result.attached, true); assert.equal(result.thumbnail.method, 'prompt-typography');
  assert.equal(db.prepare('SELECT revision FROM projects').get().revision, 2);
  const assets = db.prepare('SELECT * FROM assets').all(); assert.equal(assets.length, 3);
  for (const asset of assets) assert.ok((await fs.stat(asset.path)).size > 0);
  assert.equal(db.prepare('SELECT status FROM jobs').get().status, 'succeeded');
  assert.equal((await service.handle({ method: 'GET', pathname: '/api/thumbnail/projects/project-1' })).thumbnail.jobId, result.thumbnail.jobId);
  const inFlight = service.generate('project-1', { expectedRevision: 2, source: 'prompt', title: 'Changed while working' });
  db.prepare('UPDATE projects SET revision=3 WHERE id=?').run('project-1');
  const detached = await inFlight;
  assert.equal(detached.attached, false);
  assert.equal(JSON.parse(db.prepare('SELECT document FROM projects').get().document).thumbnailStudio.jobId, result.thumbnail.jobId);
  assert.equal(db.prepare('SELECT COUNT(*) AS count FROM assets').get().count, 6);
});
