import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { createYouTubeInsightsPanel, renderYouTubeInsightsReport } from '../youtube-insights.js';

const A='UCaaaaaaaaaaaaaaaaaaaaaa',B='UCbbbbbbbbbbbbbbbbbbbbbb';
function sample(){const id='snapshot-1';return {channel:{id:A,title:'My original channel'},connection:'channel-selected',status:'ready',settings:{enabled:false,cadenceHours:24,lastCheckAt:'2026-09-08T11:00:00Z',nextCheckAt:null},running:null,snapshot:{id,channelId:A,source:'youtube-analytics-api',startDate:'2026-08-11',endDate:'2026-09-07',fetchedAt:'2026-09-08T11:00:00Z',contentSha256:'a'.repeat(64),reports:{daily:{columnHeaders:[{name:'day'},{name:'views'},{name:'estimatedMinutesWatched'}],rows:[['2026-09-07',300,190]]},video:{columnHeaders:[{name:'video'},{name:'views'},{name:'averageViewDuration'},{name:'shares'}],rows:[['abcdefghijk',100,60,6]]}},coverage:{mayBeLimited:false}},recommendations:[{id:`${id}:average-view-duration:abcdefghijk`,kind:'average-view-duration',title:'Study higher viewing seconds',explanation:'60 seconds per view compared with 27 seconds.',caveat:'Not a retention curve or future reach prediction.',brief:'Inspect my actual source before proposing a new original follow-up.',channelId:A,videoId:'abcdefghijk',snapshotId:id,evidence:{metric:'averageViewDuration',rowIndex:0,baselineRowIndexes:[1,2],baselineMethod:'View-weighted other returned videos'}}]};}

test('snapshot render escapes strings and calls missing metrics unavailable',()=>{const s=sample();s.snapshot.id='<img src=x onerror=1>';s.snapshot.reports.daily.rows=[];const html=renderYouTubeInsightsReport(s);assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/);assert.match(html,/Unavailable views/);assert.match(html,/not a retention curve/);assert.match(html,/SHA-256/);});
test('UI reads without network-producing POST and can dispose an outstanding status read',async()=>{let resolve;const calls=[];const panel=createYouTubeInsightsPanel({api:async(p,o)=>{calls.push({p,o});return new Promise(r=>resolve=r);}});const pending=panel.update();panel.dispose();resolve(sample());await pending;assert.equal(calls.length,1);assert.equal(calls[0].o,undefined);assert.doesNotMatch(panel.html(),/My original channel/);});
test('actual browser preserves cadence draft and focus during polling; channel switch resets safely',async t=>{
 const script=await readFile(new URL('../youtube-insights.js',import.meta.url));
 const server=createServer((req,res)=>{if(req.url==='/youtube-insights.js'){res.setHeader('content-type','text/javascript');res.end(script);return;}res.setHeader('content-type','text/html');res.end(`<!doctype html><style>*{box-sizing:border-box}body{margin:0;background:#15151a;color:#eee;font:16px Arial;padding:16px}.panel{max-width:1000px;margin:auto;min-width:0}.panel-actions{display:flex;flex-wrap:wrap;gap:12px}button,select{font:inherit;padding:8px}.field{margin:12px 0}table{font-size:13px}p{line-height:1.5}.meta{color:#bcbcc5}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden}a{color:#cbbaff}</style><main></main><script type="module">import {createYouTubeInsightsPanel} from '/youtube-insights.js';window.calls=[];window.briefs=[];window.hold=false;window.fixtureStatus=null;window.panel=createYouTubeInsightsPanel({api:async(p,o)=>{if(!o)return structuredClone(window.fixtureStatus);const body=JSON.parse(o.body);window.calls.push({path:p,body});if(window.hold)await new Promise(r=>window.release=r);if(p.endsWith('/settings'))window.fixtureStatus.settings={...window.fixtureStatus.settings,...body};if(p.endsWith('/refresh'))window.fixtureStatus={...window.fixtureStatus,status:'running',running:{stage:'Reading real reports'}};return structuredClone(window.fixtureStatus);},onUseBrief:async rec=>{window.briefs.push(rec);if(window.holdBrief)await new Promise(r=>window.releaseBrief=r)}});window.mount=s=>{window.fixtureStatus=s;document.querySelector('main').innerHTML=window.panel.html();window.panel.bind()};</script>`);});
 let browser;
 // Register cleanup before either resource can fail to start. Close HTTP even if Chromium close fails.
 t.after(async()=>{server.closeAllConnections();const closed=new Promise(r=>server.close(r));try{await browser?.close();}finally{await closed;}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>typeof window.mount==='function');await page.evaluate(s=>window.mount(s),sample());await page.getByText('My original channel',{exact:false}).waitFor({timeout:3000}).catch(async error=>{throw Error(error.message+' BODY: '+await page.locator('body').innerText());});
 await page.locator('#insightsEnabled').check();await page.locator('#insightsCadence').selectOption('48');await page.locator('#insightsCadence').focus();await page.evaluate(()=>window.panel.update());assert.equal(await page.locator('#insightsCadence').inputValue(),'48');assert.equal(await page.locator('#insightsEnabled').isChecked(),true);assert.equal(await page.evaluate(()=>document.activeElement.id),'insightsCadence');assert.match(await page.locator('#youtubeInsights').innerText(),/Unsaved schedule changes/);
 const overflow=await page.evaluate(()=>({width:innerWidth,body:document.documentElement.scrollWidth}));assert.ok(overflow.body<=overflow.width+1,JSON.stringify(overflow));
 await page.evaluate(()=>window.holdBrief=true);await page.getByRole('button',{name:'Use as a new brief'}).click();await page.evaluate(()=>document.querySelector('[data-insight-brief]').dispatchEvent(new Event('click',{bubbles:true})));assert.equal(await page.evaluate(()=>window.briefs.length),1);await page.evaluate(()=>window.releaseBrief());const brief=await page.evaluate(()=>window.briefs[0]);assert.equal(brief.snapshotId,'snapshot-1');assert.equal(brief.channelId,A);assert.equal(brief.evidence.metric,'averageViewDuration');
 await page.evaluate(()=>window.hold=true);await page.getByRole('button',{name:'Save check schedule'}).click();assert.equal(await page.getByRole('button',{name:'Saving…'}).isDisabled(),true);await page.evaluate(()=>{document.querySelector('#youtubeInsightsSettings').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});assert.equal(await page.evaluate(()=>window.calls.length),1);
 await page.evaluate(id=>{window.fixtureStatus={channel:{id,title:'Second channel'},connection:'channel-selected',status:'idle',settings:{enabled:false,cadenceHours:24},snapshot:null,recommendations:[]};},B);await page.evaluate(()=>window.panel.update());await page.evaluate(()=>window.release());await page.waitForFunction(()=>!document.querySelector('#youtubeInsights').textContent.includes('Saving…'));assert.match(await page.locator('#youtubeInsights').innerText(),/Second channel/);assert.equal(await page.locator('#insightsCadence').inputValue(),'24');assert.equal(await page.locator('#insightsEnabled').isChecked(),false);assert.equal(await page.locator('[data-insight-brief]').count(),0);
 await page.evaluate(()=>window.hold=false);await page.getByRole('button',{name:'Check now'}).click();await page.getByRole('button',{name:'Check running…'}).waitFor();assert.equal(await page.evaluate(()=>window.calls.at(-1).body.channelId),B);assert.equal(await page.evaluate(()=>window.calls.filter(x=>x.path.endsWith('/refresh')).length),1);
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.panel.update());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>window.panel.dispose());
});
