import {spawn} from 'node:child_process'; import {readFile,writeFile,mkdir,stat} from 'node:fs/promises'; import {existsSync} from 'node:fs'; import {join,resolve,basename} from 'node:path'; import crypto from 'node:crypto'; import {renderTimeline} from './timeline.mjs'; import {verifyMedia} from '../runtime/media-verifier.mjs';
const args=process.argv.slice(2), val=k=>{const i=args.indexOf(k);return i>=0?args[i+1]:null}; const input=val('--input'), output=resolve(val('--output')||'./render-output');
if(!input) throw new Error('Missing --input JSON path'); await mkdir(output,{recursive:true}); const req=JSON.parse(await readFile(resolve(input),'utf8')); if(req.schemaVersion!==1) throw new Error('Unsupported schemaVersion');
const root=process.env.VYRELUM_ROOT||process.cwd(); const pick=(configured,candidates)=>{const values=configured?[configured]:candidates;const found=values.find(x=>x&&existsSync(x));return found||values[0]}; const toolRoot=resolve(root,'workers/tools'); const blender=pick(process.env.VYRELUM_BLENDER,[resolve(root,'work/render-development/tools/blender/blender-4.5.13-windows-x64/blender.exe'),resolve(toolRoot,'blender.exe')]); const ffmpeg=pick(process.env.VYRELUM_FFMPEG,[resolve(toolRoot,'ffmpeg.exe'),resolve(root,'C:/Users/lalwa/Documents/Codex/2026-08-20/open-and-read-every-file-in/work/video/kodro-ca2-rebuild/tools/ffmpeg.exe')]); const ffprobe=pick(process.env.VYRELUM_FFPROBE,[resolve(toolRoot,'ffprobe.exe'),resolve(root,'C:/Users/lalwa/Documents/Codex/2026-08-20/open-and-read-every-file-in/work/video/kodro-ca2-rebuild/tools/ffprobe.exe')]);
const run=(cmd,a)=>new Promise((res,rej)=>{const p=spawn(cmd,a,{stdio:['ignore','pipe','pipe'],windowsHide:true});let so='',se='';p.stdout.on('data',d=>so+=d);p.stderr.on('data',d=>se+=d);p.on('error',rej);p.on('close',c=>c?rej(new Error(`${basename(cmd)} exit ${c}: ${se.slice(-1500)}`)):res(so));});
let recipe={schemaVersion:1,kind:req.kind||'scene',projectId:req.projectId||null,revision:req.revision||null,createdAt:new Date().toISOString()};
let mp4=join(output,'render.mp4'), probe;
if(req.kind==='timeline') { const timelineResult=await renderTimeline(req,{output,ffmpeg,ffprobe,cacheDir:resolve(process.env.VYRELUM_RUNTIME_DIR||join(root,'data','runtime'),'timeline-cache')}); console.log(JSON.stringify(timelineResult)); process.exit(0); } else {
  const spec=req.scene||req; const py=resolve(output,'scene-request.json'); await writeFile(py,JSON.stringify({...spec,render:{...(spec.render||{}),frames:spec.render?.frames||48,fps:spec.render?.fps||24,width:spec.render?.width||640,height:spec.render?.height||360}},null,2)); await run(blender,['-b','--factory-startup','--python',resolve(root,'workers/blender_scene.py'),'--',py,output]); const pattern=join(output,'frame_%04d.png'); await run(ffmpeg,['-y','-framerate',String(spec.render?.fps||24),'-i',pattern,'-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',mp4]); recipe.scene=spec; recipe.outputs={video:'render.mp4',blend:'scene.blend',poster:'frame_0001.png'};
}
probe=JSON.parse(await run(ffprobe,['-v','error','-print_format','json','-show_streams','-show_format',mp4])); if(!probe.streams?.some(s=>s.codec_type==='video')) throw new Error('ffprobe found no video stream'); const sceneSpec=req.scene||req, sceneFrames=Number(sceneSpec.render?.frames||48), sceneFps=Number(sceneSpec.render?.fps||24); const verification=await verifyMedia({videoPath:mp4,ffprobe,ffmpeg,expected:{width:Number(sceneSpec.render?.width||640),height:Number(sceneSpec.render?.height||360),fps:sceneFps,durationSeconds:sceneFrames/sceneFps,requireAudio:false,requireVisual:true}}); if(!verification.ok) throw new Error(`Rendered output failed technical verification: ${verification.diagnostics.map(d=>d.code).join(', ')}`); recipe.outputs.ffprobe=probe; recipe.verification=verification; recipe.inputHash=crypto.createHash('sha256').update(JSON.stringify(req)).digest('hex'); await writeFile(join(output,'result.json'),JSON.stringify(recipe,null,2)); console.log(JSON.stringify(recipe));
