import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {renderTimeline} from './timeline.mjs';
const exec=promisify(execFile),ffmpeg=resolve('workers/tools/ffmpeg.exe'),ffprobe=resolve('workers/tools/ffprobe.exe');
test('mixed colour-range recordings retain every frame and reject a truncated cached base',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'vyrealm-colour-range-'));
 const run=args=>exec(ffmpeg,['-v','error','-y','-filter_threads','1',...args],{windowsHide:true,timeout:30000});
 for(const [name,range]of[['first','tv'],['second','pc']])await run(['-f','lavfi','-i','testsrc2=size=160x90:rate=24:duration=2','-f','lavfi','-i','sine=frequency=440:duration=2:sample_rate=48000','-c:v','libx264','-threads','1','-color_range',range,'-c:a','aac','-shortest',join(dir,`${name}.mp4`)]);
 await writeFile(join(dir,'list.txt'),"file 'first.mp4'\nfile 'second.mp4'\n");
 const source=join(dir,'mixed.mp4');await run(['-f','concat','-safe','0','-i',join(dir,'list.txt'),'-c','copy',source]);
 const request={schemaVersion:1,kind:'timeline',settings:{width:160,height:90,fps:24},timeline:{clips:[{kind:'video',path:source,duration:4}]}};
 const first=await renderTimeline(request,{output:join(dir,'first-out'),ffmpeg,ffprobe,cacheDir:dir});
 assert.equal(first.ffprobe.streams.find(s=>s.codec_type==='video').nb_frames,'96');
 assert.ok(Math.abs(Number(first.ffprobe.format.duration)-4)<.08);
 const base=join(dir,'cache','timeline-v1',`${first.cache.clips[0].cacheKey}.mkv`);
 await run(['-f','lavfi','-i','testsrc2=size=160x90:rate=24:duration=1','-f','lavfi','-i','sine=frequency=440:duration=1:sample_rate=48000','-c:v','libx264','-threads','1','-c:a','pcm_s16le','-shortest',base]);
 const second=await renderTimeline(request,{output:join(dir,'second-out'),ffmpeg,ffprobe,cacheDir:dir});
 assert.equal(second.cache.clips[0].cacheHit,false);
 assert.equal(second.ffprobe.streams.find(s=>s.codec_type==='video').nb_frames,'96');
 const manifest=JSON.parse(await readFile(base.replace(/\.mkv$/,'.json'),'utf8'));
 assert.equal(manifest.verification.frames,96);assert.match(manifest.outputHash,/^[a-f0-9]{64}$/);
 const third=await renderTimeline(request,{output:join(dir,'third-out'),ffmpeg,ffprobe,cacheDir:dir});
 assert.equal(third.cache.clips[0].cacheHit,true);
});
